# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'abas.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(273, 342)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../Documents/GitHub/projeto_dsoft/datails.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.aba_aula = QtWidgets.QWidget()
        self.aba_aula.setObjectName("aba_aula")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.aba_aula)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.materia = QtWidgets.QHBoxLayout()
        self.materia.setObjectName("materia")
        self.label_materia = QtWidgets.QLabel(self.aba_aula)
        self.label_materia.setObjectName("label_materia")
        self.materia.addWidget(self.label_materia)
        self.input_materia = QtWidgets.QLineEdit(self.aba_aula)
        self.input_materia.setText("")
        self.input_materia.setObjectName("input_materia")
        self.materia.addWidget(self.input_materia)
        self.verticalLayout.addLayout(self.materia)
        self.abreviacao = QtWidgets.QHBoxLayout()
        self.abreviacao.setObjectName("abreviacao")
        self.label_abreviacao = QtWidgets.QLabel(self.aba_aula)
        self.label_abreviacao.setObjectName("label_abreviacao")
        self.abreviacao.addWidget(self.label_abreviacao)
        self.input_abreviacao = QtWidgets.QLineEdit(self.aba_aula)
        self.input_abreviacao.setText("")
        self.input_abreviacao.setObjectName("input_abreviacao")
        self.abreviacao.addWidget(self.input_abreviacao)
        self.verticalLayout.addLayout(self.abreviacao)
        self.sobre_materia = QtWidgets.QVBoxLayout()
        self.sobre_materia.setObjectName("sobre_materia")
        self.label_sobremateria = QtWidgets.QLabel(self.aba_aula)
        self.label_sobremateria.setObjectName("label_sobremateria")
        self.sobre_materia.addWidget(self.label_sobremateria)
        self.input_sobremateria = QtWidgets.QTextEdit(self.aba_aula)
        self.input_sobremateria.setReadOnly(True)
        self.input_sobremateria.setObjectName("input_sobremateria")
        self.sobre_materia.addWidget(self.input_sobremateria)
        self.verticalLayout.addLayout(self.sobre_materia)
        self.professor = QtWidgets.QHBoxLayout()
        self.professor.setObjectName("professor")
        self.label_professor = QtWidgets.QLabel(self.aba_aula)
        self.label_professor.setObjectName("label_professor")
        self.professor.addWidget(self.label_professor)
        self.input_professor = QtWidgets.QLineEdit(self.aba_aula)
        self.input_professor.setText("")
        self.input_professor.setObjectName("input_professor")
        self.professor.addWidget(self.input_professor)
        self.verticalLayout.addLayout(self.professor)
        self.sobre_prof = QtWidgets.QVBoxLayout()
        self.sobre_prof.setObjectName("sobre_prof")
        self.lavel_sobreprof = QtWidgets.QLabel(self.aba_aula)
        self.lavel_sobreprof.setObjectName("lavel_sobreprof")
        self.sobre_prof.addWidget(self.lavel_sobreprof)
        self.input_sobreprof = QtWidgets.QTextEdit(self.aba_aula)
        self.input_sobreprof.setReadOnly(True)
        self.input_sobreprof.setObjectName("input_sobreprof")
        self.sobre_prof.addWidget(self.input_sobreprof)
        self.verticalLayout.addLayout(self.sobre_prof)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.aba_aula, "")
        self.aba_sala = QtWidgets.QWidget()
        self.aba_sala.setObjectName("aba_sala")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.aba_sala)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.aba_sala)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.aba_sala)
        self.lineEdit.setReadOnly(True)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.aba_sala)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.aba_sala)
        self.lineEdit_2.setReadOnly(True)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_4.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.label_3 = QtWidgets.QLabel(self.aba_sala)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.tabWidget.addTab(self.aba_sala, "")
        self.aba_tpdo = QtWidgets.QWidget()
        self.aba_tpdo.setObjectName("aba_tpdo")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.aba_tpdo)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.aba_tpdo)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(193)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.aba_tpdo)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(self.aba_tpdo)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_8.addWidget(self.pushButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.aba_tpdo)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.aba_tpdo)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_6.addWidget(self.lineEdit_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_5 = QtWidgets.QLabel(self.aba_tpdo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_7.addWidget(self.label_5)
        self.dateEdit = QtWidgets.QDateEdit(self.aba_tpdo)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2016, 1, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCurrentSection(QtWidgets.QDateTimeEdit.DaySection)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setCurrentSectionIndex(0)
        self.dateEdit.setTimeSpec(QtCore.Qt.LocalTime)
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_7.addWidget(self.dateEdit)
        self.verticalLayout_5.addLayout(self.horizontalLayout_7)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.aba_tpdo, "")
        self.horizontalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Detalhes"))
        self.label_materia.setText(_translate("Form", "Matéria"))
        self.label_abreviacao.setText(_translate("Form", "Abreviação"))
        self.label_sobremateria.setText(_translate("Form", "Sobre a matéria:"))
        self.label_professor.setText(_translate("Form", "Professor"))
        self.lavel_sobreprof.setText(_translate("Form", "Sobre o professor:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aba_aula), _translate("Form", "Aula"))
        self.label.setText(_translate("Form", "Sala"))
        self.label_2.setText(_translate("Form", "Andar"))
        self.label_3.setText(_translate("Form", "Imagem"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aba_sala), _translate("Form", "Sala"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("Form", "13/05"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Nome"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("Form", "Modsim"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_6.setText(_translate("Form", "Adicionar um lembrete"))
        self.pushButton.setText(_translate("Form", "Salvar"))
        self.label_4.setText(_translate("Form", "Nome"))
        self.label_5.setText(_translate("Form", "Data"))
        self.dateEdit.setDisplayFormat(_translate("Form", "dd/MM"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.aba_tpdo), _translate("Form", "To do"))

