# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendário_final.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
import sys


class Ui_Calendario(QtGui.QMainWindow):
    def __init__(self):
        super(Ui_Calendario, self).__init__()
        
        self.setupUi()
    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1164, 869)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Label_TituloJanela = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_TituloJanela.sizePolicy().hasHeightForWidth())
        self.Label_TituloJanela.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Label_TituloJanela.setFont(font)
        self.Label_TituloJanela.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_TituloJanela.setObjectName("Label_TituloJanela")
        self.verticalLayout.addWidget(self.Label_TituloJanela)

#---------------- Checkbox para editar a janela -----------------#        
        self.Lay_Editar_Aulas = QtGui.QHBoxLayout()
        self.Lay_Editar_Aulas.setObjectName("Lay_Editar_Aulas")
        spacerItem = QtGui.QSpacerItem(1143, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Lay_Editar_Aulas.addItem(spacerItem)
        self.checkbox_editarAula = QtGui.QCheckBox(self.centralwidget)
        self.checkbox_editarAula.setObjectName("checkbox_editarAula")
        self.Lay_Editar_Aulas.addWidget(self.checkbox_editarAula)
        self.verticalLayout.addLayout(self.Lay_Editar_Aulas)
        self.Lay_Editar_Horarios = QtGui.QHBoxLayout()
        self.Lay_Editar_Horarios.setObjectName("Lay_Editar_Horarios")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Lay_Editar_Horarios.addItem(spacerItem1)
        self.checkbox_editarHora = QtGui.QCheckBox(self.centralwidget)
        self.checkbox_editarHora.setChecked(False)
        self.checkbox_editarHora.setAutoRepeat(False)
        self.checkbox_editarHora.setAutoExclusive(False)
        self.checkbox_editarHora.setTristate(False)
        self.checkbox_editarHora.setObjectName("checkbox_editarHora")
        self.Lay_Editar_Horarios.addWidget(self.checkbox_editarHora)
        self.verticalLayout.addLayout(self.Lay_Editar_Horarios)
#-----------------------------------------------------------------#   

        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Grade_horario = QtGui.QGridLayout()
        self.Grade_horario.setObjectName("Grade_horario")
        self.D3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3_Tipo.sizePolicy().hasHeightForWidth())
        self.D3_Tipo.setSizePolicy(sizePolicy)
        self.D3_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D3_Tipo.setObjectName("D3_Tipo")
        self.verticalLayout_62 = QtGui.QVBoxLayout(self.D3_Tipo)
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.D_Labels_3 = QtGui.QVBoxLayout()
        self.D_Labels_3.setObjectName("D_Labels_3")
        self.D_Aula_3 = QtGui.QLabel(self.D3_Tipo)
        self.D_Aula_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.D_Aula_3.setAlignment(QtCore.Qt.AlignCenter)
        self.D_Aula_3.setObjectName("D_Aula_3")
        self.D_Labels_3.addWidget(self.D_Aula_3)
        self.verticalLayout_62.addLayout(self.D_Labels_3)
        self.Grade_horario.addWidget(self.D3_Tipo, 5, 7, 1, 1)
        self.D1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1_Tipo.sizePolicy().hasHeightForWidth())
        self.D1_Tipo.setSizePolicy(sizePolicy)
        self.D1_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D1_Tipo.setObjectName("D1_Tipo")
        self.verticalLayout_42 = QtGui.QVBoxLayout(self.D1_Tipo)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.D_Labels = QtGui.QVBoxLayout()
        self.D_Labels.setObjectName("D_Labels")
        self.D_Aula = QtGui.QLabel(self.D1_Tipo)
        self.D_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.D_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.D_Aula.setObjectName("D_Aula")
        self.D_Labels.addWidget(self.D_Aula)
        self.verticalLayout_42.addLayout(self.D_Labels)
        self.Grade_horario.addWidget(self.D1_Tipo, 3, 7, 1, 1)
        self.Sa1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa1_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa1_Tipo.setSizePolicy(sizePolicy)
        self.Sa1_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa1_Tipo.setObjectName("Sa1_Tipo")
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.Sa1_Tipo)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.Sa_Labels = QtGui.QVBoxLayout()
        self.Sa_Labels.setObjectName("Sa_Labels")
        self.Sa_Aula = QtGui.QLabel(self.Sa1_Tipo)
        self.Sa_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sa_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.Sa_Aula.setObjectName("Sa_Aula")
        self.Sa_Labels.addWidget(self.Sa_Aula)
        self.verticalLayout_40.addLayout(self.Sa_Labels)
        self.Grade_horario.addWidget(self.Sa1_Tipo, 3, 6, 1, 1)
        self.Sa3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa3_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa3_Tipo.setSizePolicy(sizePolicy)
        self.Sa3_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa3_Tipo.setObjectName("Sa3_Tipo")
        self.verticalLayout_60 = QtGui.QVBoxLayout(self.Sa3_Tipo)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.Sa_Labels_3 = QtGui.QVBoxLayout()
        self.Sa_Labels_3.setObjectName("Sa_Labels_3")
        self.Sa_Aula_3 = QtGui.QLabel(self.Sa3_Tipo)
        self.Sa_Aula_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sa_Aula_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Sa_Aula_3.setObjectName("Sa_Aula_3")
        self.Sa_Labels_3.addWidget(self.Sa_Aula_3)
        self.verticalLayout_60.addLayout(self.Sa_Labels_3)
        self.Grade_horario.addWidget(self.Sa3_Tipo, 5, 6, 1, 1)
        self.Sa2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa2_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa2_Tipo.setSizePolicy(sizePolicy)
        self.Sa2_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa2_Tipo.setObjectName("Sa2_Tipo")
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.Sa2_Tipo)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.Sa_Labels_2 = QtGui.QVBoxLayout()
        self.Sa_Labels_2.setObjectName("Sa_Labels_2")
        self.Sa_Aula_2 = QtGui.QLabel(self.Sa2_Tipo)
        self.Sa_Aula_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sa_Aula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Sa_Aula_2.setObjectName("Sa_Aula_2")
        self.Sa_Labels_2.addWidget(self.Sa_Aula_2)
        self.verticalLayout_38.addLayout(self.Sa_Labels_2)
        self.Grade_horario.addWidget(self.Sa2_Tipo, 4, 6, 1, 1)
        self.Label_Domingo = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Domingo.setFont(font)
        self.Label_Domingo.setFrameShape(QtGui.QFrame.Box)
        self.Label_Domingo.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Domingo.setObjectName("Label_Domingo")
        self.Grade_horario.addWidget(self.Label_Domingo, 0, 7, 1, 1)
        self.Label_Horario7 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario7.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario7.setFont(font)
        self.Label_Horario7.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario7.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario7.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario7.setObjectName("Label_Horario7")
        self.Grade_horario.addWidget(self.Label_Horario7, 9, 0, 1, 1)
        self.Label_Horario5 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario5.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario5.setFont(font)
        self.Label_Horario5.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario5.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario5.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario5.setObjectName("Label_Horario5")
        self.Grade_horario.addWidget(self.Label_Horario5, 7, 0, 1, 1)
        self.Label_Quarta = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Quarta.setFont(font)
        self.Label_Quarta.setFrameShape(QtGui.QFrame.Box)
        self.Label_Quarta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Quarta.setObjectName("Label_Quarta")
        self.Grade_horario.addWidget(self.Label_Quarta, 0, 3, 1, 1)
        self.Label_Quinta = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Quinta.setFont(font)
        self.Label_Quinta.setFrameShape(QtGui.QFrame.Box)
        self.Label_Quinta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Quinta.setObjectName("Label_Quinta")
        self.Grade_horario.addWidget(self.Label_Quinta, 0, 4, 1, 1)
        self.Qi3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi3_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi3_Tipo.setSizePolicy(sizePolicy)
        self.Qi3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi3_Tipo.setObjectName("Qi3_Tipo")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Qi3_Tipo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Qi_Labels_3 = QtGui.QVBoxLayout()
        self.Qi_Labels_3.setObjectName("Qi_Labels_3")
        self.Qi_Aula_3 = QtGui.QLabel(self.Qi3_Tipo)
        self.Qi_Aula_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Aula_3.setObjectName("Qi_Aula_3")
        self.Qi_Labels_3.addWidget(self.Qi_Aula_3)
        self.Qi_Sala_3 = QtGui.QLabel(self.Qi3_Tipo)
        self.Qi_Sala_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Sala_3.setObjectName("Qi_Sala_3")
        self.Qi_Labels_3.addWidget(self.Qi_Sala_3)
        self.verticalLayout_3.addLayout(self.Qi_Labels_3)
        self.Grade_horario.addWidget(self.Qi3_Tipo, 5, 4, 1, 1)
        self.Label_Horario3 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario3.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario3.setFont(font)
        self.Label_Horario3.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario3.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario3.setObjectName("Label_Horario3")
        self.Grade_horario.addWidget(self.Label_Horario3, 5, 0, 1, 1)
        self.Label_Sabado = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Sabado.setFont(font)
        self.Label_Sabado.setFrameShape(QtGui.QFrame.Box)
        self.Label_Sabado.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Sabado.setObjectName("Label_Sabado")
        self.Grade_horario.addWidget(self.Label_Sabado, 0, 6, 1, 1)
        self.Label_Sexta = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Sexta.setFont(font)
        self.Label_Sexta.setFrameShape(QtGui.QFrame.Box)
        self.Label_Sexta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Sexta.setObjectName("Label_Sexta")
        self.Grade_horario.addWidget(self.Label_Sexta, 0, 5, 1, 1)
        self.Label_Horario6 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario6.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario6.setFont(font)
        self.Label_Horario6.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario6.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario6.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario6.setObjectName("Label_Horario6")
        self.Grade_horario.addWidget(self.Label_Horario6, 8, 0, 1, 1)
        self.Label_Terca = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Terca.setFont(font)
        self.Label_Terca.setFrameShape(QtGui.QFrame.Box)
        self.Label_Terca.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Terca.setObjectName("Label_Terca")
        self.Grade_horario.addWidget(self.Label_Terca, 0, 2, 1, 1)
        self.Label_Horario4 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario4.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario4.setFont(font)
        self.Label_Horario4.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario4.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario4.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario4.setObjectName("Label_Horario4")
        self.Grade_horario.addWidget(self.Label_Horario4, 6, 0, 1, 1)
        self.Label_Horario2 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario2.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario2.setFont(font)
        self.Label_Horario2.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario2.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario2.setObjectName("Label_Horario2")
        self.Grade_horario.addWidget(self.Label_Horario2, 4, 0, 1, 1)
        self.Q3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q3_Tipo.sizePolicy().hasHeightForWidth())
        self.Q3_Tipo.setSizePolicy(sizePolicy)
        self.Q3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q3_Tipo.setObjectName("Q3_Tipo")
        self.verticalLayout_56 = QtGui.QVBoxLayout(self.Q3_Tipo)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.Q_Labels_3 = QtGui.QVBoxLayout()
        self.Q_Labels_3.setObjectName("Q_Labels_3")
        self.Q_Aula_3 = QtGui.QLabel(self.Q3_Tipo)
        self.Q_Aula_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Aula_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Aula_3.setObjectName("Q_Aula_3")
        self.Q_Labels_3.addWidget(self.Q_Aula_3)
        self.Q_Sala_3 = QtGui.QLabel(self.Q3_Tipo)
        self.Q_Sala_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Sala_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Sala_3.setObjectName("Q_Sala_3")
        self.Q_Labels_3.addWidget(self.Q_Sala_3)
        self.verticalLayout_56.addLayout(self.Q_Labels_3)
        self.Grade_horario.addWidget(self.Q3_Tipo, 5, 3, 1, 1)
        self.D2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2_Tipo.sizePolicy().hasHeightForWidth())
        self.D2_Tipo.setSizePolicy(sizePolicy)
        self.D2_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D2_Tipo.setObjectName("D2_Tipo")
        self.verticalLayout_64 = QtGui.QVBoxLayout(self.D2_Tipo)
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.D_Labels_2 = QtGui.QVBoxLayout()
        self.D_Labels_2.setObjectName("D_Labels_2")
        self.D_Aula_2 = QtGui.QLabel(self.D2_Tipo)
        self.D_Aula_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.D_Aula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.D_Aula_2.setObjectName("D_Aula_2")
        self.D_Labels_2.addWidget(self.D_Aula_2)
        self.verticalLayout_64.addLayout(self.D_Labels_2)
        self.Grade_horario.addWidget(self.D2_Tipo, 4, 7, 1, 1)
        self.Label_Segunda = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Segunda.setFont(font)
        self.Label_Segunda.setFrameShape(QtGui.QFrame.Box)
        self.Label_Segunda.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Segunda.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Label_Segunda.setObjectName("Label_Segunda")
        self.Grade_horario.addWidget(self.Label_Segunda, 0, 1, 1, 1)
        self.Label_Horario1 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario1.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario1.setFont(font)
        self.Label_Horario1.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario1.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario1.setObjectName("Label_Horario1")
        self.Grade_horario.addWidget(self.Label_Horario1, 3, 0, 1, 1)
        self.T7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T7_Tipo.sizePolicy().hasHeightForWidth())
        self.T7_Tipo.setSizePolicy(sizePolicy)
        self.T7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T7_Tipo.setObjectName("T7_Tipo")
        self.verticalLayout_50 = QtGui.QVBoxLayout(self.T7_Tipo)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.T_Labels_7 = QtGui.QVBoxLayout()
        self.T_Labels_7.setObjectName("T_Labels_7")
        self.T_Aula_7 = QtGui.QLabel(self.T7_Tipo)
        self.T_Aula_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Aula_7.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Aula_7.setObjectName("T_Aula_7")
        self.T_Labels_7.addWidget(self.T_Aula_7)
        self.T_Sala_7 = QtGui.QLabel(self.T7_Tipo)
        self.T_Sala_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Sala_7.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Sala_7.setObjectName("T_Sala_7")
        self.T_Labels_7.addWidget(self.T_Sala_7)
        self.verticalLayout_50.addLayout(self.T_Labels_7)
        self.Grade_horario.addWidget(self.T7_Tipo, 9, 2, 1, 1)
        self.S7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S7_Tipo.sizePolicy().hasHeightForWidth())
        self.S7_Tipo.setSizePolicy(sizePolicy)
        self.S7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S7_Tipo.setCheckable(False)
        self.S7_Tipo.setObjectName("S7_Tipo")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.S7_Tipo)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.S_Labels_7 = QtGui.QVBoxLayout()
        self.S_Labels_7.setObjectName("S_Labels_7")
        self.S_Aula_7 = QtGui.QLabel(self.S7_Tipo)
        self.S_Aula_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Aula_7.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Aula_7.setObjectName("S_Aula_7")
        self.S_Labels_7.addWidget(self.S_Aula_7)
        self.S_Sala_7 = QtGui.QLabel(self.S7_Tipo)
        self.S_Sala_7.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Sala_7.setObjectName("S_Sala_7")
        self.S_Labels_7.addWidget(self.S_Sala_7)
        self.verticalLayout_21.addLayout(self.S_Labels_7)
        self.Grade_horario.addWidget(self.S7_Tipo, 9, 1, 1, 1)
        self.T5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T5_Tipo.sizePolicy().hasHeightForWidth())
        self.T5_Tipo.setSizePolicy(sizePolicy)
        self.T5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T5_Tipo.setObjectName("T5_Tipo")
        self.verticalLayout_46 = QtGui.QVBoxLayout(self.T5_Tipo)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.T_Labels_5 = QtGui.QVBoxLayout()
        self.T_Labels_5.setObjectName("T_Labels_5")
        self.T_Aula_5 = QtGui.QLabel(self.T5_Tipo)
        self.T_Aula_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Aula_5.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Aula_5.setObjectName("T_Aula_5")
        self.T_Labels_5.addWidget(self.T_Aula_5)
        self.T_Sala_5 = QtGui.QLabel(self.T5_Tipo)
        self.T_Sala_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Sala_5.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Sala_5.setObjectName("T_Sala_5")
        self.T_Labels_5.addWidget(self.T_Sala_5)
        self.verticalLayout_46.addLayout(self.T_Labels_5)
        self.Grade_horario.addWidget(self.T5_Tipo, 7, 2, 1, 1)
        self.S6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S6_Tipo.sizePolicy().hasHeightForWidth())
        self.S6_Tipo.setSizePolicy(sizePolicy)
        self.S6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S6_Tipo.setCheckable(False)
        self.S6_Tipo.setObjectName("S6_Tipo")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.S6_Tipo)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.S_Labels_6 = QtGui.QVBoxLayout()
        self.S_Labels_6.setObjectName("S_Labels_6")
        self.S_Aula_6 = QtGui.QLabel(self.S6_Tipo)
        self.S_Aula_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Aula_6.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Aula_6.setObjectName("S_Aula_6")
        self.S_Labels_6.addWidget(self.S_Aula_6)
        self.S_Sala_6 = QtGui.QLabel(self.S6_Tipo)
        self.S_Sala_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Sala_6.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Sala_6.setObjectName("S_Sala_6")
        self.S_Labels_6.addWidget(self.S_Sala_6)
        self.verticalLayout_19.addLayout(self.S_Labels_6)
        self.Grade_horario.addWidget(self.S6_Tipo, 8, 1, 1, 1)
        self.S5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S5_Tipo.sizePolicy().hasHeightForWidth())
        self.S5_Tipo.setSizePolicy(sizePolicy)
        self.S5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S5_Tipo.setAutoFillBackground(True)
        self.S5_Tipo.setFlat(False)
        self.S5_Tipo.setCheckable(False)
        self.S5_Tipo.setChecked(False)
        self.S5_Tipo.setObjectName("S5_Tipo")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.S5_Tipo)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.S_Labels_5 = QtGui.QVBoxLayout()
        self.S_Labels_5.setObjectName("S_Labels_5")
        self.S_Aula_5 = QtGui.QLabel(self.S5_Tipo)
        self.S_Aula_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Aula_5.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Aula_5.setObjectName("S_Aula_5")
        self.S_Labels_5.addWidget(self.S_Aula_5)
        self.S_Sala_5 = QtGui.QLabel(self.S5_Tipo)
        self.S_Sala_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Sala_5.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Sala_5.setObjectName("S_Sala_5")
        self.S_Labels_5.addWidget(self.S_Sala_5)
        self.verticalLayout_17.addLayout(self.S_Labels_5)
        self.Grade_horario.addWidget(self.S5_Tipo, 7, 1, 1, 1)
        self.S4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S4_Tipo.sizePolicy().hasHeightForWidth())
        self.S4_Tipo.setSizePolicy(sizePolicy)
        self.S4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S4_Tipo.setCheckable(False)
        self.S4_Tipo.setObjectName("S4_Tipo")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.S4_Tipo)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.S_Labels_4 = QtGui.QVBoxLayout()
        self.S_Labels_4.setObjectName("S_Labels_4")
        self.S_Aula_4 = QtGui.QLabel(self.S4_Tipo)
        self.S_Aula_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Aula_4.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Aula_4.setObjectName("S_Aula_4")
        self.S_Labels_4.addWidget(self.S_Aula_4)
        self.S_Sala_4 = QtGui.QLabel(self.S4_Tipo)
        self.S_Sala_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Sala_4.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Sala_4.setObjectName("S_Sala_4")
        self.S_Labels_4.addWidget(self.S_Sala_4)
        self.verticalLayout_15.addLayout(self.S_Labels_4)
        self.Grade_horario.addWidget(self.S4_Tipo, 6, 1, 1, 1)
        self.T6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T6_Tipo.sizePolicy().hasHeightForWidth())
        self.T6_Tipo.setSizePolicy(sizePolicy)
        self.T6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T6_Tipo.setObjectName("T6_Tipo")
        self.verticalLayout_48 = QtGui.QVBoxLayout(self.T6_Tipo)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.T_Labels_6 = QtGui.QVBoxLayout()
        self.T_Labels_6.setObjectName("T_Labels_6")
        self.T_Aula_6 = QtGui.QLabel(self.T6_Tipo)
        self.T_Aula_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Aula_6.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Aula_6.setObjectName("T_Aula_6")
        self.T_Labels_6.addWidget(self.T_Aula_6)
        self.T_Sala_6 = QtGui.QLabel(self.T6_Tipo)
        self.T_Sala_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Sala_6.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Sala_6.setObjectName("T_Sala_6")
        self.T_Labels_6.addWidget(self.T_Sala_6)
        self.verticalLayout_48.addLayout(self.T_Labels_6)
        self.Grade_horario.addWidget(self.T6_Tipo, 8, 2, 1, 1)
        self.Qi5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi5_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi5_Tipo.setSizePolicy(sizePolicy)
        self.Qi5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi5_Tipo.setObjectName("Qi5_Tipo")
        self.verticalLayout_66 = QtGui.QVBoxLayout(self.Qi5_Tipo)
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.Qi_Labels_5 = QtGui.QVBoxLayout()
        self.Qi_Labels_5.setObjectName("Qi_Labels_5")
        self.Qi_Aula_5 = QtGui.QLabel(self.Qi5_Tipo)
        self.Qi_Aula_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Aula_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Aula_5.setObjectName("Qi_Aula_5")
        self.Qi_Labels_5.addWidget(self.Qi_Aula_5)
        self.Qi_Sala_5 = QtGui.QLabel(self.Qi5_Tipo)
        self.Qi_Sala_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Sala_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Sala_5.setObjectName("Qi_Sala_5")
        self.Qi_Labels_5.addWidget(self.Qi_Sala_5)
        self.verticalLayout_66.addLayout(self.Qi_Labels_5)
        self.Grade_horario.addWidget(self.Qi5_Tipo, 7, 4, 1, 1)
        self.Q5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q5_Tipo.sizePolicy().hasHeightForWidth())
        self.Q5_Tipo.setSizePolicy(sizePolicy)
        self.Q5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q5_Tipo.setObjectName("Q5_Tipo")
        self.verticalLayout_52 = QtGui.QVBoxLayout(self.Q5_Tipo)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.Q_Labels_5 = QtGui.QVBoxLayout()
        self.Q_Labels_5.setObjectName("Q_Labels_5")
        self.Q_Aula_5 = QtGui.QLabel(self.Q5_Tipo)
        self.Q_Aula_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Aula_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Aula_5.setObjectName("Q_Aula_5")
        self.Q_Labels_5.addWidget(self.Q_Aula_5)
        self.Q_Sala_5 = QtGui.QLabel(self.Q5_Tipo)
        self.Q_Sala_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Sala_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Sala_5.setObjectName("Q_Sala_5")
        self.Q_Labels_5.addWidget(self.Q_Sala_5)
        self.verticalLayout_52.addLayout(self.Q_Labels_5)
        self.Grade_horario.addWidget(self.Q5_Tipo, 7, 3, 1, 1)
        self.Q4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q4_Tipo.sizePolicy().hasHeightForWidth())
        self.Q4_Tipo.setSizePolicy(sizePolicy)
        self.Q4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q4_Tipo.setObjectName("Q4_Tipo")
        self.verticalLayout_54 = QtGui.QVBoxLayout(self.Q4_Tipo)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.Q_Labels_4 = QtGui.QVBoxLayout()
        self.Q_Labels_4.setObjectName("Q_Labels_4")
        self.Q_Aula_4 = QtGui.QLabel(self.Q4_Tipo)
        self.Q_Aula_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Aula_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Aula_4.setObjectName("Q_Aula_4")
        self.Q_Labels_4.addWidget(self.Q_Aula_4)
        self.Q_Sala_4 = QtGui.QLabel(self.Q4_Tipo)
        self.Q_Sala_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Sala_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Sala_4.setObjectName("Q_Sala_4")
        self.Q_Labels_4.addWidget(self.Q_Sala_4)
        self.verticalLayout_54.addLayout(self.Q_Labels_4)
        self.Grade_horario.addWidget(self.Q4_Tipo, 6, 3, 1, 1)
        self.Q6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q6_Tipo.sizePolicy().hasHeightForWidth())
        self.Q6_Tipo.setSizePolicy(sizePolicy)
        self.Q6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q6_Tipo.setObjectName("Q6_Tipo")
        self.verticalLayout_78 = QtGui.QVBoxLayout(self.Q6_Tipo)
        self.verticalLayout_78.setObjectName("verticalLayout_78")
        self.Q_Labels_6 = QtGui.QVBoxLayout()
        self.Q_Labels_6.setObjectName("Q_Labels_6")
        self.Q_Aula_6 = QtGui.QLabel(self.Q6_Tipo)
        self.Q_Aula_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Aula_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Aula_6.setObjectName("Q_Aula_6")
        self.Q_Labels_6.addWidget(self.Q_Aula_6)
        self.Q_Sala_6 = QtGui.QLabel(self.Q6_Tipo)
        self.Q_Sala_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Sala_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Sala_6.setObjectName("Q_Sala_6")
        self.Q_Labels_6.addWidget(self.Q_Sala_6)
        self.verticalLayout_78.addLayout(self.Q_Labels_6)
        self.Grade_horario.addWidget(self.Q6_Tipo, 8, 3, 1, 1)
        self.Qi4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi4_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi4_Tipo.setSizePolicy(sizePolicy)
        self.Qi4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi4_Tipo.setObjectName("Qi4_Tipo")
        self.verticalLayout_68 = QtGui.QVBoxLayout(self.Qi4_Tipo)
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.Qi_Labels_4 = QtGui.QVBoxLayout()
        self.Qi_Labels_4.setObjectName("Qi_Labels_4")
        self.Qi_Aula_4 = QtGui.QLabel(self.Qi4_Tipo)
        self.Qi_Aula_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Aula_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Aula_4.setObjectName("Qi_Aula_4")
        self.Qi_Labels_4.addWidget(self.Qi_Aula_4)
        self.Qi_Sala_4 = QtGui.QLabel(self.Qi4_Tipo)
        self.Qi_Sala_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Sala_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Sala_4.setObjectName("Qi_Sala_4")
        self.Qi_Labels_4.addWidget(self.Qi_Sala_4)
        self.verticalLayout_68.addLayout(self.Qi_Labels_4)
        self.Grade_horario.addWidget(self.Qi4_Tipo, 6, 4, 1, 1)
        self.T4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T4_Tipo.sizePolicy().hasHeightForWidth())
        self.T4_Tipo.setSizePolicy(sizePolicy)
        self.T4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T4_Tipo.setObjectName("T4_Tipo")
        self.verticalLayout_44 = QtGui.QVBoxLayout(self.T4_Tipo)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.T_Labels_4 = QtGui.QVBoxLayout()
        self.T_Labels_4.setObjectName("T_Labels_4")
        self.T_Aula_4 = QtGui.QLabel(self.T4_Tipo)
        self.T_Aula_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Aula_4.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Aula_4.setObjectName("T_Aula_4")
        self.T_Labels_4.addWidget(self.T_Aula_4)
        self.T_Sala_4 = QtGui.QLabel(self.T4_Tipo)
        self.T_Sala_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Sala_4.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Sala_4.setObjectName("T_Sala_4")
        self.T_Labels_4.addWidget(self.T_Sala_4)
        self.verticalLayout_44.addLayout(self.T_Labels_4)
        self.Grade_horario.addWidget(self.T4_Tipo, 6, 2, 1, 1)
        self.Q7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q7_Tipo.sizePolicy().hasHeightForWidth())
        self.Q7_Tipo.setSizePolicy(sizePolicy)
        self.Q7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q7_Tipo.setObjectName("Q7_Tipo")
        self.verticalLayout_76 = QtGui.QVBoxLayout(self.Q7_Tipo)
        self.verticalLayout_76.setObjectName("verticalLayout_76")
        self.Q_Labels_7 = QtGui.QVBoxLayout()
        self.Q_Labels_7.setObjectName("Q_Labels_7")
        self.Q_Aula_7 = QtGui.QLabel(self.Q7_Tipo)
        self.Q_Aula_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Aula_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Aula_7.setObjectName("Q_Aula_7")
        self.Q_Labels_7.addWidget(self.Q_Aula_7)
        self.Q_Sala_7 = QtGui.QLabel(self.Q7_Tipo)
        self.Q_Sala_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Sala_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Sala_7.setObjectName("Q_Sala_7")
        self.Q_Labels_7.addWidget(self.Q_Sala_7)
        self.verticalLayout_76.addLayout(self.Q_Labels_7)
        self.Grade_horario.addWidget(self.Q7_Tipo, 9, 3, 1, 1)
        self.Sx4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx4_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx4_Tipo.setSizePolicy(sizePolicy)
        self.Sx4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx4_Tipo.setObjectName("Sx4_Tipo")
        self.verticalLayout_70 = QtGui.QVBoxLayout(self.Sx4_Tipo)
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.Sx_Labels_4 = QtGui.QVBoxLayout()
        self.Sx_Labels_4.setObjectName("Sx_Labels_4")
        self.Sx_Aula_4 = QtGui.QLabel(self.Sx4_Tipo)
        self.Sx_Aula_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Aula_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Aula_4.setObjectName("Sx_Aula_4")
        self.Sx_Labels_4.addWidget(self.Sx_Aula_4)
        self.Sx_Sala_4 = QtGui.QLabel(self.Sx4_Tipo)
        self.Sx_Sala_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Sala_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Sala_4.setObjectName("Sx_Sala_4")
        self.Sx_Labels_4.addWidget(self.Sx_Sala_4)
        self.verticalLayout_70.addLayout(self.Sx_Labels_4)
        self.Grade_horario.addWidget(self.Sx4_Tipo, 6, 5, 1, 1)
        self.Sx3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx3_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx3_Tipo.setSizePolicy(sizePolicy)
        self.Sx3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx3_Tipo.setObjectName("Sx3_Tipo")
        self.verticalLayout_58 = QtGui.QVBoxLayout(self.Sx3_Tipo)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.Sx_Labels_3 = QtGui.QVBoxLayout()
        self.Sx_Labels_3.setObjectName("Sx_Labels_3")
        self.Sx_Aula_3 = QtGui.QLabel(self.Sx3_Tipo)
        self.Sx_Aula_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Aula_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Aula_3.setObjectName("Sx_Aula_3")
        self.Sx_Labels_3.addWidget(self.Sx_Aula_3)
        self.Sx_Sala_3 = QtGui.QLabel(self.Sx3_Tipo)
        self.Sx_Sala_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Sala_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Sala_3.setObjectName("Sx_Sala_3")
        self.Sx_Labels_3.addWidget(self.Sx_Sala_3)
        self.verticalLayout_58.addLayout(self.Sx_Labels_3)
        self.Grade_horario.addWidget(self.Sx3_Tipo, 5, 5, 1, 1)
        self.Qi6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi6_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi6_Tipo.setSizePolicy(sizePolicy)
        self.Qi6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi6_Tipo.setObjectName("Qi6_Tipo")
        self.verticalLayout_80 = QtGui.QVBoxLayout(self.Qi6_Tipo)
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.Qi_Labels_6 = QtGui.QVBoxLayout()
        self.Qi_Labels_6.setObjectName("Qi_Labels_6")
        self.Qi_Aula_6 = QtGui.QLabel(self.Qi6_Tipo)
        self.Qi_Aula_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Aula_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Aula_6.setObjectName("Qi_Aula_6")
        self.Qi_Labels_6.addWidget(self.Qi_Aula_6)
        self.Qi_Sala_6 = QtGui.QLabel(self.Qi6_Tipo)
        self.Qi_Sala_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Sala_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Sala_6.setObjectName("Qi_Sala_6")
        self.Qi_Labels_6.addWidget(self.Qi_Sala_6)
        self.verticalLayout_80.addLayout(self.Qi_Labels_6)
        self.Grade_horario.addWidget(self.Qi6_Tipo, 8, 4, 1, 1)
        self.D4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4_Tipo.sizePolicy().hasHeightForWidth())
        self.D4_Tipo.setSizePolicy(sizePolicy)
        self.D4_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D4_Tipo.setObjectName("D4_Tipo")
        self.verticalLayout_96 = QtGui.QVBoxLayout(self.D4_Tipo)
        self.verticalLayout_96.setObjectName("verticalLayout_96")
        self.D_Labels_4 = QtGui.QVBoxLayout()
        self.D_Labels_4.setObjectName("D_Labels_4")
        self.D_Aula_4 = QtGui.QLabel(self.D4_Tipo)
        self.D_Aula_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.D_Aula_4.setAlignment(QtCore.Qt.AlignCenter)
        self.D_Aula_4.setObjectName("D_Aula_4")
        self.D_Labels_4.addWidget(self.D_Aula_4)
        self.verticalLayout_96.addLayout(self.D_Labels_4)
        self.Grade_horario.addWidget(self.D4_Tipo, 6, 7, 1, 1)
        self.Sx7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx7_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx7_Tipo.setSizePolicy(sizePolicy)
        self.Sx7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx7_Tipo.setObjectName("Sx7_Tipo")
        self.verticalLayout_86 = QtGui.QVBoxLayout(self.Sx7_Tipo)
        self.verticalLayout_86.setObjectName("verticalLayout_86")
        self.Sx_Labels_7 = QtGui.QVBoxLayout()
        self.Sx_Labels_7.setObjectName("Sx_Labels_7")
        self.Sx_Aula_7 = QtGui.QLabel(self.Sx7_Tipo)
        self.Sx_Aula_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Aula_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Aula_7.setObjectName("Sx_Aula_7")
        self.Sx_Labels_7.addWidget(self.Sx_Aula_7)
        self.Sx_Sala_7 = QtGui.QLabel(self.Sx7_Tipo)
        self.Sx_Sala_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Sala_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Sala_7.setObjectName("Sx_Sala_7")
        self.Sx_Labels_7.addWidget(self.Sx_Sala_7)
        self.verticalLayout_86.addLayout(self.Sx_Labels_7)
        self.Grade_horario.addWidget(self.Sx7_Tipo, 9, 5, 1, 1)
        self.Sx6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx6_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx6_Tipo.setSizePolicy(sizePolicy)
        self.Sx6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx6_Tipo.setObjectName("Sx6_Tipo")
        self.verticalLayout_82 = QtGui.QVBoxLayout(self.Sx6_Tipo)
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.Sx_Labels_6 = QtGui.QVBoxLayout()
        self.Sx_Labels_6.setObjectName("Sx_Labels_6")
        self.Sx_Aula_6 = QtGui.QLabel(self.Sx6_Tipo)
        self.Sx_Aula_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Aula_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Aula_6.setObjectName("Sx_Aula_6")
        self.Sx_Labels_6.addWidget(self.Sx_Aula_6)
        self.Sx_Sala_6 = QtGui.QLabel(self.Sx6_Tipo)
        self.Sx_Sala_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Sala_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Sala_6.setObjectName("Sx_Sala_6")
        self.Sx_Labels_6.addWidget(self.Sx_Sala_6)
        self.verticalLayout_82.addLayout(self.Sx_Labels_6)
        self.Grade_horario.addWidget(self.Sx6_Tipo, 8, 5, 1, 1)
        self.Qi7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi7_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi7_Tipo.setSizePolicy(sizePolicy)
        self.Qi7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi7_Tipo.setObjectName("Qi7_Tipo")
        self.verticalLayout_84 = QtGui.QVBoxLayout(self.Qi7_Tipo)
        self.verticalLayout_84.setObjectName("verticalLayout_84")
        self.Qi_Labels_7 = QtGui.QVBoxLayout()
        self.Qi_Labels_7.setObjectName("Qi_Labels_7")
        self.Qi_Aula_7 = QtGui.QLabel(self.Qi7_Tipo)
        self.Qi_Aula_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Aula_7.setObjectName("Qi_Aula_7")
        self.Qi_Labels_7.addWidget(self.Qi_Aula_7)
        self.Qi_Sala_7 = QtGui.QLabel(self.Qi7_Tipo)
        self.Qi_Sala_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Sala_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Sala_7.setObjectName("Qi_Sala_7")
        self.Qi_Labels_7.addWidget(self.Qi_Sala_7)
        self.verticalLayout_84.addLayout(self.Qi_Labels_7)
        self.Grade_horario.addWidget(self.Qi7_Tipo, 9, 4, 1, 1)
        self.Sx5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx5_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx5_Tipo.setSizePolicy(sizePolicy)
        self.Sx5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx5_Tipo.setObjectName("Sx5_Tipo")
        self.verticalLayout_74 = QtGui.QVBoxLayout(self.Sx5_Tipo)
        self.verticalLayout_74.setObjectName("verticalLayout_74")
        self.Sx_Labels_5 = QtGui.QVBoxLayout()
        self.Sx_Labels_5.setObjectName("Sx_Labels_5")
        self.Sx_Aula_5 = QtGui.QLabel(self.Sx5_Tipo)
        self.Sx_Aula_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Aula_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Aula_5.setObjectName("Sx_Aula_5")
        self.Sx_Labels_5.addWidget(self.Sx_Aula_5)
        self.Sx_Sala_5 = QtGui.QLabel(self.Sx5_Tipo)
        self.Sx_Sala_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Sala_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Sala_5.setObjectName("Sx_Sala_5")
        self.Sx_Labels_5.addWidget(self.Sx_Sala_5)
        self.verticalLayout_74.addLayout(self.Sx_Labels_5)
        self.Grade_horario.addWidget(self.Sx5_Tipo, 7, 5, 1, 1)
        self.D6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6_Tipo.sizePolicy().hasHeightForWidth())
        self.D6_Tipo.setSizePolicy(sizePolicy)
        self.D6_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D6_Tipo.setObjectName("D6_Tipo")
        self.verticalLayout_100 = QtGui.QVBoxLayout(self.D6_Tipo)
        self.verticalLayout_100.setObjectName("verticalLayout_100")
        self.D_Labels_6 = QtGui.QVBoxLayout()
        self.D_Labels_6.setObjectName("D_Labels_6")
        self.D_Aula_6 = QtGui.QLabel(self.D6_Tipo)
        self.D_Aula_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.D_Aula_6.setAlignment(QtCore.Qt.AlignCenter)
        self.D_Aula_6.setObjectName("D_Aula_6")
        self.D_Labels_6.addWidget(self.D_Aula_6)
        self.verticalLayout_100.addLayout(self.D_Labels_6)
        self.Grade_horario.addWidget(self.D6_Tipo, 8, 7, 1, 1)
        self.D5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5_Tipo.sizePolicy().hasHeightForWidth())
        self.D5_Tipo.setSizePolicy(sizePolicy)
        self.D5_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D5_Tipo.setObjectName("D5_Tipo")
        self.verticalLayout_94 = QtGui.QVBoxLayout(self.D5_Tipo)
        self.verticalLayout_94.setObjectName("verticalLayout_94")
        self.D_Labels_5 = QtGui.QVBoxLayout()
        self.D_Labels_5.setObjectName("D_Labels_5")
        self.D_Aula_5 = QtGui.QLabel(self.D5_Tipo)
        self.D_Aula_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.D_Aula_5.setAlignment(QtCore.Qt.AlignCenter)
        self.D_Aula_5.setObjectName("D_Aula_5")
        self.D_Labels_5.addWidget(self.D_Aula_5)
        self.verticalLayout_94.addLayout(self.D_Labels_5)
        self.Grade_horario.addWidget(self.D5_Tipo, 7, 7, 1, 1)
        self.Sa4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa4_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa4_Tipo.setSizePolicy(sizePolicy)
        self.Sa4_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa4_Tipo.setObjectName("Sa4_Tipo")
        self.verticalLayout_72 = QtGui.QVBoxLayout(self.Sa4_Tipo)
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.Sa_Labels_4 = QtGui.QVBoxLayout()
        self.Sa_Labels_4.setObjectName("Sa_Labels_4")
        self.Sa_Aula_4 = QtGui.QLabel(self.Sa4_Tipo)
        self.Sa_Aula_4.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sa_Aula_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Sa_Aula_4.setObjectName("Sa_Aula_4")
        self.Sa_Labels_4.addWidget(self.Sa_Aula_4)
        self.verticalLayout_72.addLayout(self.Sa_Labels_4)
        self.Grade_horario.addWidget(self.Sa4_Tipo, 6, 6, 1, 1)
        self.Sa5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa5_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa5_Tipo.setSizePolicy(sizePolicy)
        self.Sa5_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa5_Tipo.setObjectName("Sa5_Tipo")
        self.verticalLayout_92 = QtGui.QVBoxLayout(self.Sa5_Tipo)
        self.verticalLayout_92.setObjectName("verticalLayout_92")
        self.Sa_Labels_5 = QtGui.QVBoxLayout()
        self.Sa_Labels_5.setObjectName("Sa_Labels_5")
        self.Sa_Aula_5 = QtGui.QLabel(self.Sa5_Tipo)
        self.Sa_Aula_5.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sa_Aula_5.setAlignment(QtCore.Qt.AlignCenter)
        self.Sa_Aula_5.setObjectName("Sa_Aula_5")
        self.Sa_Labels_5.addWidget(self.Sa_Aula_5)
        self.verticalLayout_92.addLayout(self.Sa_Labels_5)
        self.Grade_horario.addWidget(self.Sa5_Tipo, 7, 6, 1, 1)
        self.Sa7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa7_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa7_Tipo.setSizePolicy(sizePolicy)
        self.Sa7_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa7_Tipo.setObjectName("Sa7_Tipo")
        self.verticalLayout_88 = QtGui.QVBoxLayout(self.Sa7_Tipo)
        self.verticalLayout_88.setObjectName("verticalLayout_88")
        self.Sa_Labels_7 = QtGui.QVBoxLayout()
        self.Sa_Labels_7.setObjectName("Sa_Labels_7")
        self.Sa_Aula_7 = QtGui.QLabel(self.Sa7_Tipo)
        self.Sa_Aula_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sa_Aula_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Sa_Aula_7.setObjectName("Sa_Aula_7")
        self.Sa_Labels_7.addWidget(self.Sa_Aula_7)
        self.verticalLayout_88.addLayout(self.Sa_Labels_7)
        self.Grade_horario.addWidget(self.Sa7_Tipo, 9, 6, 1, 1)
        self.D7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7_Tipo.sizePolicy().hasHeightForWidth())
        self.D7_Tipo.setSizePolicy(sizePolicy)
        self.D7_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D7_Tipo.setObjectName("D7_Tipo")
        self.verticalLayout_98 = QtGui.QVBoxLayout(self.D7_Tipo)
        self.verticalLayout_98.setObjectName("verticalLayout_98")
        self.D_Labels_7 = QtGui.QVBoxLayout()
        self.D_Labels_7.setObjectName("D_Labels_7")
        self.D_Aula_7 = QtGui.QLabel(self.D7_Tipo)
        self.D_Aula_7.setFrameShape(QtGui.QFrame.NoFrame)
        self.D_Aula_7.setAlignment(QtCore.Qt.AlignCenter)
        self.D_Aula_7.setObjectName("D_Aula_7")
        self.D_Labels_7.addWidget(self.D_Aula_7)
        self.verticalLayout_98.addLayout(self.D_Labels_7)
        self.Grade_horario.addWidget(self.D7_Tipo, 9, 7, 1, 1)
        self.Sa6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa6_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa6_Tipo.setSizePolicy(sizePolicy)
        self.Sa6_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa6_Tipo.setObjectName("Sa6_Tipo")
        self.verticalLayout_90 = QtGui.QVBoxLayout(self.Sa6_Tipo)
        self.verticalLayout_90.setObjectName("verticalLayout_90")
        self.Sa_Labels_6 = QtGui.QVBoxLayout()
        self.Sa_Labels_6.setObjectName("Sa_Labels_6")
        self.Sa_Aula_6 = QtGui.QLabel(self.Sa6_Tipo)
        self.Sa_Aula_6.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sa_Aula_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Sa_Aula_6.setObjectName("Sa_Aula_6")
        self.Sa_Labels_6.addWidget(self.Sa_Aula_6)
        self.verticalLayout_90.addLayout(self.Sa_Labels_6)
        self.Grade_horario.addWidget(self.Sa6_Tipo, 8, 6, 1, 1)
        self.Sx2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx2_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx2_Tipo.setSizePolicy(sizePolicy)
        self.Sx2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx2_Tipo.setObjectName("Sx2_Tipo")
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.Sx2_Tipo)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.Sx_Labels_2 = QtGui.QVBoxLayout()
        self.Sx_Labels_2.setObjectName("Sx_Labels_2")
        self.Sx_Aula_2 = QtGui.QLabel(self.Sx2_Tipo)
        self.Sx_Aula_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Aula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Aula_2.setObjectName("Sx_Aula_2")
        self.Sx_Labels_2.addWidget(self.Sx_Aula_2)
        self.Sx_Sala_2 = QtGui.QLabel(self.Sx2_Tipo)
        self.Sx_Sala_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Sala_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Sala_2.setObjectName("Sx_Sala_2")
        self.Sx_Labels_2.addWidget(self.Sx_Sala_2)
        self.verticalLayout_36.addLayout(self.Sx_Labels_2)
        self.Grade_horario.addWidget(self.Sx2_Tipo, 4, 5, 1, 1)
        self.Sx1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx1_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx1_Tipo.setSizePolicy(sizePolicy)
        self.Sx1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx1_Tipo.setObjectName("Sx1_Tipo")
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.Sx1_Tipo)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.Sx_Labels = QtGui.QVBoxLayout()
        self.Sx_Labels.setObjectName("Sx_Labels")
        self.Sx_Aula = QtGui.QLabel(self.Sx1_Tipo)
        self.Sx_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Aula.setObjectName("Sx_Aula")
        self.Sx_Labels.addWidget(self.Sx_Aula)
        self.Sx_Sala = QtGui.QLabel(self.Sx1_Tipo)
        self.Sx_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.Sx_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.Sx_Sala.setObjectName("Sx_Sala")
        self.Sx_Labels.addWidget(self.Sx_Sala)
        self.verticalLayout_34.addLayout(self.Sx_Labels)
        self.Grade_horario.addWidget(self.Sx1_Tipo, 3, 5, 1, 1)
        self.Qi1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi1_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi1_Tipo.setSizePolicy(sizePolicy)
        self.Qi1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi1_Tipo.setObjectName("Qi1_Tipo")
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.Qi1_Tipo)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.Qi_Labels = QtGui.QVBoxLayout()
        self.Qi_Labels.setObjectName("Qi_Labels")
        self.Qi_Aula = QtGui.QLabel(self.Qi1_Tipo)
        self.Qi_Aula.setObjectName("Qi_Aula")
        self.Qi_Labels.addWidget(self.Qi_Aula)
        self.Qi_Sala = QtGui.QLabel(self.Qi1_Tipo)
        self.Qi_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Sala.setObjectName("Qi_Sala")
        self.Qi_Labels.addWidget(self.Qi_Sala)
        self.verticalLayout_32.addLayout(self.Qi_Labels)
        self.Grade_horario.addWidget(self.Qi1_Tipo, 3, 4, 1, 1)
        self.T1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T1_Tipo.sizePolicy().hasHeightForWidth())
        self.T1_Tipo.setSizePolicy(sizePolicy)
        self.T1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T1_Tipo.setObjectName("T1_Tipo")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.T1_Tipo)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.T_Labels = QtGui.QVBoxLayout()
        self.T_Labels.setObjectName("T_Labels")
        self.T_Aula = QtGui.QLabel(self.T1_Tipo)
        self.T_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Aula.setObjectName("T_Aula")
        self.T_Labels.addWidget(self.T_Aula)
        self.T_Sala = QtGui.QLabel(self.T1_Tipo)
        self.T_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Sala.setObjectName("T_Sala")
        self.T_Labels.addWidget(self.T_Sala)
        self.verticalLayout_9.addLayout(self.T_Labels)
        self.Grade_horario.addWidget(self.T1_Tipo, 3, 2, 1, 1)
        self.Q1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q1_Tipo.sizePolicy().hasHeightForWidth())
        self.Q1_Tipo.setSizePolicy(sizePolicy)
        self.Q1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q1_Tipo.setObjectName("Q1_Tipo")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.Q1_Tipo)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.Q_Labels = QtGui.QVBoxLayout()
        self.Q_Labels.setObjectName("Q_Labels")
        self.Q_Aula = QtGui.QLabel(self.Q1_Tipo)
        self.Q_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Aula.setObjectName("Q_Aula")
        self.Q_Labels.addWidget(self.Q_Aula)
        self.Q_Sala = QtGui.QLabel(self.Q1_Tipo)
        self.Q_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Sala.setObjectName("Q_Sala")
        self.Q_Labels.addWidget(self.Q_Sala)
        self.verticalLayout_11.addLayout(self.Q_Labels)
        self.Grade_horario.addWidget(self.Q1_Tipo, 3, 3, 1, 1)
        self.S2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S2_Tipo.sizePolicy().hasHeightForWidth())
        self.S2_Tipo.setSizePolicy(sizePolicy)
        self.S2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S2_Tipo.setCheckable(False)
        self.S2_Tipo.setObjectName("S2_Tipo")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.S2_Tipo)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.S_Labels_2 = QtGui.QVBoxLayout()
        self.S_Labels_2.setObjectName("S_Labels_2")
        self.S_Aula_2 = QtGui.QLabel(self.S2_Tipo)
        self.S_Aula_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Aula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Aula_2.setObjectName("S_Aula_2")
        self.S_Labels_2.addWidget(self.S_Aula_2)
        self.S_Sala_2 = QtGui.QLabel(self.S2_Tipo)
        self.S_Sala_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Sala_2.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Sala_2.setObjectName("S_Sala_2")
        self.S_Labels_2.addWidget(self.S_Sala_2)
        self.verticalLayout_5.addLayout(self.S_Labels_2)
        self.Grade_horario.addWidget(self.S2_Tipo, 4, 1, 1, 1)
        self.S1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S1_Tipo.sizePolicy().hasHeightForWidth())
        self.S1_Tipo.setSizePolicy(sizePolicy)
        self.S1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S1_Tipo.setCheckable(False)
        self.S1_Tipo.setObjectName("S1_Tipo")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.S1_Tipo)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.S_Labels = QtGui.QVBoxLayout()
        self.S_Labels.setObjectName("S_Labels")
        self.S_Aula = QtGui.QLabel(self.S1_Tipo)
        self.S_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Aula.setObjectName("S_Aula")
        self.S_Labels.addWidget(self.S_Aula)
        self.S_Sala = QtGui.QLabel(self.S1_Tipo)
        self.S_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Sala.setObjectName("S_Sala")
        self.S_Labels.addWidget(self.S_Sala)
        self.verticalLayout_7.addLayout(self.S_Labels)
        self.Grade_horario.addWidget(self.S1_Tipo, 3, 1, 1, 1)
        self.S3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S3_Tipo.sizePolicy().hasHeightForWidth())
        self.S3_Tipo.setSizePolicy(sizePolicy)
        self.S3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S3_Tipo.setCheckable(False)
        self.S3_Tipo.setObjectName("S3_Tipo")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.S3_Tipo)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.S_Labels_3 = QtGui.QVBoxLayout()
        self.S_Labels_3.setObjectName("S_Labels_3")
        self.S_Aula_3 = QtGui.QLabel(self.S3_Tipo)
        self.S_Aula_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Aula_3.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Aula_3.setObjectName("S_Aula_3")
        self.S_Labels_3.addWidget(self.S_Aula_3)
        self.S_Sala_3 = QtGui.QLabel(self.S3_Tipo)
        self.S_Sala_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.S_Sala_3.setAlignment(QtCore.Qt.AlignCenter)
        self.S_Sala_3.setObjectName("S_Sala_3")
        self.S_Labels_3.addWidget(self.S_Sala_3)
        self.verticalLayout_13.addLayout(self.S_Labels_3)
        self.Grade_horario.addWidget(self.S3_Tipo, 5, 1, 1, 1)
        self.Qi2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi2_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi2_Tipo.setSizePolicy(sizePolicy)
        self.Qi2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi2_Tipo.setObjectName("Qi2_Tipo")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.Qi2_Tipo)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.Qi_Labels_2 = QtGui.QVBoxLayout()
        self.Qi_Labels_2.setObjectName("Qi_Labels_2")
        self.Qi_Aula_2 = QtGui.QLabel(self.Qi2_Tipo)
        self.Qi_Aula_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Aula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Aula_2.setObjectName("Qi_Aula_2")
        self.Qi_Labels_2.addWidget(self.Qi_Aula_2)
        self.Qi_Sala_2 = QtGui.QLabel(self.Qi2_Tipo)
        self.Qi_Sala_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.Qi_Sala_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Qi_Sala_2.setObjectName("Qi_Sala_2")
        self.Qi_Labels_2.addWidget(self.Qi_Sala_2)
        self.verticalLayout_30.addLayout(self.Qi_Labels_2)
        self.Grade_horario.addWidget(self.Qi2_Tipo, 4, 4, 1, 1)
        self.Q2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q2_Tipo.sizePolicy().hasHeightForWidth())
        self.Q2_Tipo.setSizePolicy(sizePolicy)
        self.Q2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q2_Tipo.setObjectName("Q2_Tipo")
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.Q2_Tipo)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.Q_Labels_2 = QtGui.QVBoxLayout()
        self.Q_Labels_2.setObjectName("Q_Labels_2")
        self.Q_Aula_2 = QtGui.QLabel(self.Q2_Tipo)
        self.Q_Aula_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Aula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Aula_2.setObjectName("Q_Aula_2")
        self.Q_Labels_2.addWidget(self.Q_Aula_2)
        self.Q_Sala_2 = QtGui.QLabel(self.Q2_Tipo)
        self.Q_Sala_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q_Sala_2.setAlignment(QtCore.Qt.AlignCenter)
        self.Q_Sala_2.setObjectName("Q_Sala_2")
        self.Q_Labels_2.addWidget(self.Q_Sala_2)
        self.verticalLayout_28.addLayout(self.Q_Labels_2)
        self.Grade_horario.addWidget(self.Q2_Tipo, 4, 3, 1, 1)
        self.T2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T2_Tipo.sizePolicy().hasHeightForWidth())
        self.T2_Tipo.setSizePolicy(sizePolicy)
        self.T2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T2_Tipo.setObjectName("T2_Tipo")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.T2_Tipo)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.T_Labels_2 = QtGui.QVBoxLayout()
        self.T_Labels_2.setObjectName("T_Labels_2")
        self.T_Aula_2 = QtGui.QLabel(self.T2_Tipo)
        self.T_Aula_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Aula_2.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Aula_2.setObjectName("T_Aula_2")
        self.T_Labels_2.addWidget(self.T_Aula_2)
        self.T_Sala_2 = QtGui.QLabel(self.T2_Tipo)
        self.T_Sala_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Sala_2.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Sala_2.setObjectName("T_Sala_2")
        self.T_Labels_2.addWidget(self.T_Sala_2)
        self.verticalLayout_24.addLayout(self.T_Labels_2)
        self.Grade_horario.addWidget(self.T2_Tipo, 4, 2, 1, 1)
        self.T3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T3_Tipo.sizePolicy().hasHeightForWidth())
        self.T3_Tipo.setSizePolicy(sizePolicy)
        self.T3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T3_Tipo.setObjectName("T3_Tipo")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.T3_Tipo)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.T_Labels_3 = QtGui.QVBoxLayout()
        self.T_Labels_3.setObjectName("T_Labels_3")
        self.T_Aula_3 = QtGui.QLabel(self.T3_Tipo)
        self.T_Aula_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Aula_3.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Aula_3.setObjectName("T_Aula_3")
        self.T_Labels_3.addWidget(self.T_Aula_3)
        self.T_Sala_3 = QtGui.QLabel(self.T3_Tipo)
        self.T_Sala_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.T_Sala_3.setAlignment(QtCore.Qt.AlignCenter)
        self.T_Sala_3.setObjectName("T_Sala_3")
        self.T_Labels_3.addWidget(self.T_Sala_3)
        self.verticalLayout_26.addLayout(self.T_Labels_3)
        self.Grade_horario.addWidget(self.T3_Tipo, 5, 2, 1, 1)
        self.Label_Horarios = QtGui.QLabel(self.centralwidget)
        self.Label_Horarios.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horarios.setFont(font)
        self.Label_Horarios.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horarios.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horarios.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horarios.setObjectName("Label_Horarios")
        self.Grade_horario.addWidget(self.Label_Horarios, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.Grade_horario)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Calendário Semanal"))
        self.Label_TituloJanela.setText(_translate("MainWindow", "Calendário Semanal da Sala"))
        self.checkbox_editarAula.setText(_translate("MainWindow", "Editar Aulas"))
        self.checkbox_editarHora.setText(_translate("MainWindow", "Editar Horários"))
        self.D3_Tipo.setTitle(_translate("MainWindow", "Horário 3"))
        self.D_Aula_3.setText(_translate("MainWindow", "-"))
        self.D1_Tipo.setTitle(_translate("MainWindow", "Horário 1"))
        self.D_Aula.setText(_translate("MainWindow", "-"))
        self.Sa1_Tipo.setTitle(_translate("MainWindow", "Horário 1"))
        self.Sa_Aula.setText(_translate("MainWindow", "-"))
        self.Sa3_Tipo.setTitle(_translate("MainWindow", "Horário 3"))
        self.Sa_Aula_3.setText(_translate("MainWindow", "-"))
        self.Sa2_Tipo.setTitle(_translate("MainWindow", "Horário 2"))
        self.Sa_Aula_2.setText(_translate("MainWindow", "-"))
        self.Label_Domingo.setText(_translate("MainWindow", "Domingo"))
        self.Label_Horario7.setText(_translate("MainWindow", "20h15 - 22h15"))
        self.Label_Horario5.setText(_translate("MainWindow", "15h45 - 17h45"))
        self.Label_Quarta.setText(_translate("MainWindow", "Quarta-feira"))
        self.Label_Quinta.setText(_translate("MainWindow", "Quinta-feira"))
        self.Qi3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.Qi_Aula_3.setText(_translate("MainWindow", "-"))
        self.Qi_Sala_3.setText(_translate("MainWindow", "-"))
        self.Label_Horario3.setText(_translate("MainWindow", "11h45 - 13h30"))
        self.Label_Sabado.setText(_translate("MainWindow", "Sábado"))
        self.Label_Sexta.setText(_translate("MainWindow", "Sexta-feira"))
        self.Label_Horario6.setText(_translate("MainWindow", "18h00 - 20h00"))
        self.Label_Terca.setText(_translate("MainWindow", "Terça-feira"))
        self.Label_Horario4.setText(_translate("MainWindow", "13h30 - 15h30"))
        self.Label_Horario2.setText(_translate("MainWindow", "09h45 - 11h45"))
        self.Q3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.Q_Aula_3.setText(_translate("MainWindow", "-"))
        self.Q_Sala_3.setText(_translate("MainWindow", "-"))
        self.D2_Tipo.setTitle(_translate("MainWindow", "Horário 2"))
        self.D_Aula_2.setText(_translate("MainWindow", "-"))
        self.Label_Segunda.setText(_translate("MainWindow", "Segunda-feira"))
        self.Label_Horario1.setText(_translate("MainWindow", "07h30 - 09h30"))
        self.T7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.T_Aula_7.setText(_translate("MainWindow", "-"))
        self.T_Sala_7.setText(_translate("MainWindow", "-"))
        self.S7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.S_Aula_7.setText(_translate("MainWindow", "-"))
        self.S_Sala_7.setText(_translate("MainWindow", "-"))
        self.T5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.T_Aula_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Instrumentação </span></p><p align=\"center\"><span style=\" font-weight:600;\">e Medição</span></p></body></html>"))
        self.T_Sala_5.setText(_translate("MainWindow", "Sala 401"))
        self.S6_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.S_Aula_6.setText(_translate("MainWindow", "-"))
        self.S_Sala_6.setText(_translate("MainWindow", "-"))
        self.S5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.S_Aula_5.setText(_translate("MainWindow", "-"))
        self.S_Sala_5.setText(_translate("MainWindow", "-"))
        self.S4_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.S_Aula_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação</span></p><p align=\"center\"><span style=\" font-weight:600;\"> do Mundo Físico</span></p></body></html>"))
        self.S_Sala_4.setText(_translate("MainWindow", "Sala 403"))
        self.T6_Tipo.setTitle(_translate("MainWindow", "Aula 5"))
        self.T_Aula_6.setText(_translate("MainWindow", "-"))
        self.T_Sala_6.setText(_translate("MainWindow", "-"))
        self.Qi5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Qi_Aula_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação </span></p><p align=\"center\"><span style=\" font-weight:600;\">do Mundo Físico</span></p></body></html>"))
        self.Qi_Sala_5.setText(_translate("MainWindow", "Sala 403"))
        self.Q5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Q_Aula_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Natureza do Design</span></p></body></html>"))
        self.Q_Sala_5.setText(_translate("MainWindow", "Sala 403"))
        self.Q4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Q_Aula_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Natureza do Design</span></p></body></html>"))
        self.Q_Sala_4.setText(_translate("MainWindow", "Sala 403"))
        self.Q6_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.Q_Aula_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Natureza do Design</span></p></body></html>"))
        self.Q_Sala_6.setText(_translate("MainWindow", "Fablab"))
        self.Qi4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Qi_Aula_4.setText(_translate("MainWindow", "-"))
        self.Qi_Sala_4.setText(_translate("MainWindow", "-"))
        self.T4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.T_Aula_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Instrumentação</span></p><p align=\"center\"><span style=\" font-weight:600;\">e Medição</span></p></body></html>"))
        self.T_Sala_4.setText(_translate("MainWindow", "Sala 401"))
        self.Q7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Q_Aula_7.setText(_translate("MainWindow", "-"))
        self.Q_Sala_7.setText(_translate("MainWindow", "-"))
        self.Sx4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Sx_Aula_4.setText(_translate("MainWindow", "-"))
        self.Sx_Sala_4.setText(_translate("MainWindow", "-"))
        self.Sx3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.Sx_Aula_3.setText(_translate("MainWindow", "-"))
        self.Sx_Sala_3.setText(_translate("MainWindow", "-"))
        self.Qi6_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Qi_Aula_6.setText(_translate("MainWindow", "-"))
        self.Qi_Sala_6.setText(_translate("MainWindow", "-"))
        self.D4_Tipo.setTitle(_translate("MainWindow", "Horário 4"))
        self.D_Aula_4.setText(_translate("MainWindow", "-"))
        self.Sx7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Sx_Aula_7.setText(_translate("MainWindow", "-"))
        self.Sx_Sala_7.setText(_translate("MainWindow", "-"))
        self.Sx6_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Sx_Aula_6.setText(_translate("MainWindow", "-"))
        self.Sx_Sala_6.setText(_translate("MainWindow", "-"))
        self.Qi7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Qi_Aula_7.setText(_translate("MainWindow", "-"))
        self.Qi_Sala_7.setText(_translate("MainWindow", "-"))
        self.Sx5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Sx_Aula_5.setText(_translate("MainWindow", "-"))
        self.Sx_Sala_5.setText(_translate("MainWindow", "-"))
        self.D6_Tipo.setTitle(_translate("MainWindow", "Horário 6"))
        self.D_Aula_6.setText(_translate("MainWindow", "-"))
        self.D5_Tipo.setTitle(_translate("MainWindow", "Horário 5"))
        self.D_Aula_5.setText(_translate("MainWindow", "-"))
        self.Sa4_Tipo.setTitle(_translate("MainWindow", "Horário 4"))
        self.Sa_Aula_4.setText(_translate("MainWindow", "-"))
        self.Sa5_Tipo.setTitle(_translate("MainWindow", "Horário 5"))
        self.Sa_Aula_5.setText(_translate("MainWindow", "-"))
        self.Sa7_Tipo.setTitle(_translate("MainWindow", "Horário 7"))
        self.Sa_Aula_7.setText(_translate("MainWindow", "-"))
        self.D7_Tipo.setTitle(_translate("MainWindow", "Horário 7"))
        self.D_Aula_7.setText(_translate("MainWindow", "-"))
        self.Sa6_Tipo.setTitle(_translate("MainWindow", "Horário 6"))
        self.Sa_Aula_6.setText(_translate("MainWindow", "-"))
        self.Sx2_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Sx_Aula_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação</span></p><p align=\"center\"><span style=\" font-weight:600;\"> do Mundo Físico</span></p></body></html>"))
        self.Sx_Sala_2.setText(_translate("MainWindow", "Sala 403"))
        self.Sx1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Sx_Aula.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Design de Software</span></p></body></html>"))
        self.Sx_Sala.setText(_translate("MainWindow", "Sala 403"))
        self.Qi1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Qi_Aula.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios </span></p><p align=\"center\"><span style=\" font-weight:600;\">da Engenharia</span></p></body></html>"))
        self.Qi_Sala.setText(_translate("MainWindow", "Sala 307"))
        self.T1_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.T_Aula.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Instrumentação </span></p><p align=\"center\"><span style=\" font-weight:600;\">e Medição</span></p></body></html>"))
        self.T_Sala.setText(_translate("MainWindow", "Sala 401"))
        self.Q1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.Q_Aula.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Design de Software</span></p></body></html>"))
        self.Q_Sala.setText(_translate("MainWindow", "Sala 403"))
        self.S2_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.S_Aula_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação</span></p><p align=\"center\"><span style=\" font-weight:600;\">do Mundo Físico</span></p></body></html>"))
        self.S_Sala_2.setText(_translate("MainWindow", "Sala 403"))
        self.S1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.S_Aula.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios </span></p><p align=\"center\"><span style=\" font-weight:600;\">da Engenharia</span></p></body></html>"))
        self.S_Sala.setText(_translate("MainWindow", "Sala Marcos Lopes (2)"))
        self.S3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.S_Aula_3.setText(_translate("MainWindow", "-"))
        self.S_Sala_3.setText(_translate("MainWindow", "-"))
        self.Qi2_Tipo.setTitle(_translate("MainWindow", "Tutoria"))
        self.Qi_Aula_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios</span></p><p align=\"center\"><span style=\" font-weight:600;\"> da Engenharia</span></p></body></html>"))
        self.Qi_Sala_2.setText(_translate("MainWindow", "Sala 408"))
        self.Q2_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.Q_Aula_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios </span></p><p align=\"center\"><span style=\" font-weight:600;\">da Engenharia</span></p></body></html>"))
        self.Q_Sala_2.setText(_translate("MainWindow", "Sala 403"))
        self.T2_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.T_Aula_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Design de Software</span></p></body></html>"))
        self.T_Sala_2.setText(_translate("MainWindow", "<html><head/><body><p>Sala Alberto Bandeira</p><p>Queiroz (2)</p></body></html>"))
        self.T3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.T_Aula_3.setText(_translate("MainWindow", "-"))
        self.T_Sala_3.setText(_translate("MainWindow", "-"))
        self.Label_Horarios.setText(_translate("MainWindow", "Horários"))


if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    mainwindow = Ui_Calendario()
    mainwindow.show()
    sys.exit(app.exec_())