# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendario_final.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui, QtGui
import sys


class Ui_MainWindow(QtGui.QMainWindow):
    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        
        self.setupUi()

    def setupUi(self):
        self.setObjectName("MainWindow")
        self.resize(1164, 869)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("calendar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Label_TituloJanela = QtGui.QLabel(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Label_TituloJanela.sizePolicy().hasHeightForWidth())
        self.Label_TituloJanela.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Label_TituloJanela.setFont(font)
        self.Label_TituloJanela.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_TituloJanela.setObjectName("Label_TituloJanela")
        self.verticalLayout.addWidget(self.Label_TituloJanela)
        self.Lay_Editar_Aulas = QtGui.QHBoxLayout()
        self.Lay_Editar_Aulas.setObjectName("Lay_Editar_Aulas")
        spacerItem = QtGui.QSpacerItem(1143, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Lay_Editar_Aulas.addItem(spacerItem)
        self.checkBox_2 = QtGui.QCheckBox(self.centralwidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.Lay_Editar_Aulas.addWidget(self.checkBox_2)
        self.verticalLayout.addLayout(self.Lay_Editar_Aulas)
        self.Lay_Editar_Horarios = QtGui.QHBoxLayout()
        self.Lay_Editar_Horarios.setObjectName("Lay_Editar_Horarios")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.Lay_Editar_Horarios.addItem(spacerItem1)
        self.checkBox = QtGui.QCheckBox(self.centralwidget)
        self.checkBox.setChecked(False)
        self.checkBox.setAutoRepeat(False)
        self.checkBox.setAutoExclusive(False)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.Lay_Editar_Horarios.addWidget(self.checkBox)
        self.verticalLayout.addLayout(self.Lay_Editar_Horarios)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Grade_horario = QtGui.QGridLayout()
        self.Grade_horario.setObjectName("Grade_horario")
        self.D3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D3_Tipo.sizePolicy().hasHeightForWidth())
        self.D3_Tipo.setSizePolicy(sizePolicy)
        self.D3_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D3_Tipo.setObjectName("D3_Tipo")
        self.verticalLayout_62 = QtGui.QVBoxLayout(self.D3_Tipo)
        self.verticalLayout_62.setObjectName("verticalLayout_62")
        self.verticalLayout_61 = QtGui.QVBoxLayout()
        self.verticalLayout_61.setObjectName("verticalLayout_61")
        self.label_99 = QtGui.QLabel(self.D3_Tipo)
        self.label_99.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_99.setAlignment(QtCore.Qt.AlignCenter)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_61.addWidget(self.label_99)
        self.verticalLayout_62.addLayout(self.verticalLayout_61)
        self.Grade_horario.addWidget(self.D3_Tipo, 5, 7, 1, 1)
        self.D1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D1_Tipo.sizePolicy().hasHeightForWidth())
        self.D1_Tipo.setSizePolicy(sizePolicy)
        self.D1_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D1_Tipo.setObjectName("D1_Tipo")
        self.verticalLayout_42 = QtGui.QVBoxLayout(self.D1_Tipo)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.verticalLayout_41 = QtGui.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_90 = QtGui.QLabel(self.D1_Tipo)
        self.label_90.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_90.setAlignment(QtCore.Qt.AlignCenter)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_41.addWidget(self.label_90)
        self.verticalLayout_42.addLayout(self.verticalLayout_41)
        self.Grade_horario.addWidget(self.D1_Tipo, 3, 7, 1, 1)
        self.Sa1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa1_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa1_Tipo.setSizePolicy(sizePolicy)
        self.Sa1_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa1_Tipo.setObjectName("Sa1_Tipo")
        self.verticalLayout_40 = QtGui.QVBoxLayout(self.Sa1_Tipo)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.verticalLayout_39 = QtGui.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_89 = QtGui.QLabel(self.Sa1_Tipo)
        self.label_89.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_89.setAlignment(QtCore.Qt.AlignCenter)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_39.addWidget(self.label_89)
        self.verticalLayout_40.addLayout(self.verticalLayout_39)
        self.Grade_horario.addWidget(self.Sa1_Tipo, 3, 6, 1, 1)
        self.Sa3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa3_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa3_Tipo.setSizePolicy(sizePolicy)
        self.Sa3_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa3_Tipo.setObjectName("Sa3_Tipo")
        self.verticalLayout_60 = QtGui.QVBoxLayout(self.Sa3_Tipo)
        self.verticalLayout_60.setObjectName("verticalLayout_60")
        self.verticalLayout_59 = QtGui.QVBoxLayout()
        self.verticalLayout_59.setObjectName("verticalLayout_59")
        self.label_87 = QtGui.QLabel(self.Sa3_Tipo)
        self.label_87.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_87.setAlignment(QtCore.Qt.AlignCenter)
        self.label_87.setObjectName("label_87")
        self.verticalLayout_59.addWidget(self.label_87)
        self.verticalLayout_60.addLayout(self.verticalLayout_59)
        self.Grade_horario.addWidget(self.Sa3_Tipo, 5, 6, 1, 1)
        self.Sa2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa2_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa2_Tipo.setSizePolicy(sizePolicy)
        self.Sa2_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa2_Tipo.setObjectName("Sa2_Tipo")
        self.verticalLayout_38 = QtGui.QVBoxLayout(self.Sa2_Tipo)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.verticalLayout_37 = QtGui.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_88 = QtGui.QLabel(self.Sa2_Tipo)
        self.label_88.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_88.setAlignment(QtCore.Qt.AlignCenter)
        self.label_88.setObjectName("label_88")
        self.verticalLayout_37.addWidget(self.label_88)
        self.verticalLayout_38.addLayout(self.verticalLayout_37)
        self.Grade_horario.addWidget(self.Sa2_Tipo, 4, 6, 1, 1)
        self.Label_Domingo = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Domingo.setFont(font)
        self.Label_Domingo.setFrameShape(QtGui.QFrame.Box)
        self.Label_Domingo.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Domingo.setObjectName("Label_Domingo")
        self.Grade_horario.addWidget(self.Label_Domingo, 0, 7, 1, 1)
        self.Label_Horario7 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario7.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario7.setFont(font)
        self.Label_Horario7.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario7.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario7.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario7.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario7.setObjectName("Label_Horario7")
        self.Grade_horario.addWidget(self.Label_Horario7, 9, 0, 1, 1)
        self.Label_Horario5 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario5.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario5.setFont(font)
        self.Label_Horario5.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario5.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario5.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario5.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario5.setObjectName("Label_Horario5")
        self.Grade_horario.addWidget(self.Label_Horario5, 7, 0, 1, 1)
        self.Label_Quarta = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Quarta.setFont(font)
        self.Label_Quarta.setFrameShape(QtGui.QFrame.Box)
        self.Label_Quarta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Quarta.setObjectName("Label_Quarta")
        self.Grade_horario.addWidget(self.Label_Quarta, 0, 3, 1, 1)
        self.Label_Quinta = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Quinta.setFont(font)
        self.Label_Quinta.setFrameShape(QtGui.QFrame.Box)
        self.Label_Quinta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Quinta.setObjectName("Label_Quinta")
        self.Grade_horario.addWidget(self.Label_Quinta, 0, 4, 1, 1)
        self.Qi3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi3_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi3_Tipo.setSizePolicy(sizePolicy)
        self.Qi3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi3_Tipo.setObjectName("Qi3_Tipo")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.Qi3_Tipo)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtGui.QLabel(self.Qi3_Tipo)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtGui.QLabel(self.Qi3_Tipo)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.Grade_horario.addWidget(self.Qi3_Tipo, 5, 4, 1, 1)
        self.Label_Horario3 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario3.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario3.setFont(font)
        self.Label_Horario3.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario3.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario3.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario3.setObjectName("Label_Horario3")
        self.Grade_horario.addWidget(self.Label_Horario3, 5, 0, 1, 1)
        self.Label_Sabado = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Sabado.setFont(font)
        self.Label_Sabado.setFrameShape(QtGui.QFrame.Box)
        self.Label_Sabado.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Sabado.setObjectName("Label_Sabado")
        self.Grade_horario.addWidget(self.Label_Sabado, 0, 6, 1, 1)
        self.Label_Sexta = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Sexta.setFont(font)
        self.Label_Sexta.setFrameShape(QtGui.QFrame.Box)
        self.Label_Sexta.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Sexta.setObjectName("Label_Sexta")
        self.Grade_horario.addWidget(self.Label_Sexta, 0, 5, 1, 1)
        self.Label_Horario6 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario6.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario6.setFont(font)
        self.Label_Horario6.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario6.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario6.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario6.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario6.setObjectName("Label_Horario6")
        self.Grade_horario.addWidget(self.Label_Horario6, 8, 0, 1, 1)
        self.Label_Terca = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Terca.setFont(font)
        self.Label_Terca.setFrameShape(QtGui.QFrame.Box)
        self.Label_Terca.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Terca.setObjectName("Label_Terca")
        self.Grade_horario.addWidget(self.Label_Terca, 0, 2, 1, 1)
        self.Label_Horario4 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario4.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario4.setFont(font)
        self.Label_Horario4.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario4.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario4.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario4.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario4.setObjectName("Label_Horario4")
        self.Grade_horario.addWidget(self.Label_Horario4, 6, 0, 1, 1)
        self.Label_Horario2 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario2.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario2.setFont(font)
        self.Label_Horario2.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario2.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario2.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario2.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario2.setObjectName("Label_Horario2")
        self.Grade_horario.addWidget(self.Label_Horario2, 4, 0, 1, 1)
        self.Q3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q3_Tipo.sizePolicy().hasHeightForWidth())
        self.Q3_Tipo.setSizePolicy(sizePolicy)
        self.Q3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q3_Tipo.setObjectName("Q3_Tipo")
        self.verticalLayout_56 = QtGui.QVBoxLayout(self.Q3_Tipo)
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.Q3_Labels = QtGui.QVBoxLayout()
        self.Q3_Labels.setObjectName("Q3_Labels")
        self.Q3_Aula = QtGui.QLabel(self.Q3_Tipo)
        self.Q3_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q3_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.Q3_Aula.setObjectName("Q3_Aula")
        self.Q3_Labels.addWidget(self.Q3_Aula)
        self.Q3_Sala = QtGui.QLabel(self.Q3_Tipo)
        self.Q3_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.Q3_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.Q3_Sala.setObjectName("Q3_Sala")
        self.Q3_Labels.addWidget(self.Q3_Sala)
        self.verticalLayout_56.addLayout(self.Q3_Labels)
        self.Grade_horario.addWidget(self.Q3_Tipo, 5, 3, 1, 1)
        self.D2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D2_Tipo.sizePolicy().hasHeightForWidth())
        self.D2_Tipo.setSizePolicy(sizePolicy)
        self.D2_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D2_Tipo.setObjectName("D2_Tipo")
        self.verticalLayout_64 = QtGui.QVBoxLayout(self.D2_Tipo)
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.verticalLayout_63 = QtGui.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.label_91 = QtGui.QLabel(self.D2_Tipo)
        self.label_91.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_91.setAlignment(QtCore.Qt.AlignCenter)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_63.addWidget(self.label_91)
        self.verticalLayout_64.addLayout(self.verticalLayout_63)
        self.Grade_horario.addWidget(self.D2_Tipo, 4, 7, 1, 1)
        self.Label_Segunda = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Segunda.setFont(font)
        self.Label_Segunda.setFrameShape(QtGui.QFrame.Box)
        self.Label_Segunda.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Segunda.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse)
        self.Label_Segunda.setObjectName("Label_Segunda")
        self.Grade_horario.addWidget(self.Label_Segunda, 0, 1, 1, 1)
        self.Label_Horario1 = QtGui.QLabel(self.centralwidget)
        self.Label_Horario1.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horario1.setFont(font)
        self.Label_Horario1.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horario1.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horario1.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horario1.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.Label_Horario1.setObjectName("Label_Horario1")
        self.Grade_horario.addWidget(self.Label_Horario1, 3, 0, 1, 1)
        self.T7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T7_Tipo.sizePolicy().hasHeightForWidth())
        self.T7_Tipo.setSizePolicy(sizePolicy)
        self.T7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T7_Tipo.setObjectName("T7_Tipo")
        self.verticalLayout_50 = QtGui.QVBoxLayout(self.T7_Tipo)
        self.verticalLayout_50.setObjectName("verticalLayout_50")
        self.verticalLayout_49 = QtGui.QVBoxLayout()
        self.verticalLayout_49.setObjectName("verticalLayout_49")
        self.label_37 = QtGui.QLabel(self.T7_Tipo)
        self.label_37.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_49.addWidget(self.label_37)
        self.label_36 = QtGui.QLabel(self.T7_Tipo)
        self.label_36.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_49.addWidget(self.label_36)
        self.verticalLayout_50.addLayout(self.verticalLayout_49)
        self.Grade_horario.addWidget(self.T7_Tipo, 9, 2, 1, 1)
        self.S7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S7_Tipo.sizePolicy().hasHeightForWidth())
        self.S7_Tipo.setSizePolicy(sizePolicy)
        self.S7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S7_Tipo.setCheckable(False)
        self.S7_Tipo.setObjectName("S7_Tipo")
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.S7_Tipo)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.verticalLayout_20 = QtGui.QVBoxLayout()
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_34 = QtGui.QLabel(self.S7_Tipo)
        self.label_34.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_20.addWidget(self.label_34)
        self.label_35 = QtGui.QLabel(self.S7_Tipo)
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_20.addWidget(self.label_35)
        self.verticalLayout_21.addLayout(self.verticalLayout_20)
        self.Grade_horario.addWidget(self.S7_Tipo, 9, 1, 1, 1)
        self.T5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T5_Tipo.sizePolicy().hasHeightForWidth())
        self.T5_Tipo.setSizePolicy(sizePolicy)
        self.T5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T5_Tipo.setObjectName("T5_Tipo")
        self.verticalLayout_46 = QtGui.QVBoxLayout(self.T5_Tipo)
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.verticalLayout_45 = QtGui.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_39 = QtGui.QLabel(self.T5_Tipo)
        self.label_39.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_45.addWidget(self.label_39)
        self.label_42 = QtGui.QLabel(self.T5_Tipo)
        self.label_42.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_45.addWidget(self.label_42)
        self.verticalLayout_46.addLayout(self.verticalLayout_45)
        self.Grade_horario.addWidget(self.T5_Tipo, 7, 2, 1, 1)
        self.S6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S6_Tipo.sizePolicy().hasHeightForWidth())
        self.S6_Tipo.setSizePolicy(sizePolicy)
        self.S6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S6_Tipo.setCheckable(False)
        self.S6_Tipo.setObjectName("S6_Tipo")
        self.verticalLayout_19 = QtGui.QVBoxLayout(self.S6_Tipo)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_32 = QtGui.QLabel(self.S6_Tipo)
        self.label_32.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_18.addWidget(self.label_32)
        self.label_33 = QtGui.QLabel(self.S6_Tipo)
        self.label_33.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_33.setAlignment(QtCore.Qt.AlignCenter)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_18.addWidget(self.label_33)
        self.verticalLayout_19.addLayout(self.verticalLayout_18)
        self.Grade_horario.addWidget(self.S6_Tipo, 8, 1, 1, 1)
        self.S5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S5_Tipo.sizePolicy().hasHeightForWidth())
        self.S5_Tipo.setSizePolicy(sizePolicy)
        self.S5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S5_Tipo.setAutoFillBackground(True)
        self.S5_Tipo.setFlat(False)
        self.S5_Tipo.setCheckable(False)
        self.S5_Tipo.setChecked(False)
        self.S5_Tipo.setObjectName("S5_Tipo")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.S5_Tipo)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_31 = QtGui.QLabel(self.S5_Tipo)
        self.label_31.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_31.setAlignment(QtCore.Qt.AlignCenter)
        self.label_31.setObjectName("label_31")
        self.verticalLayout_16.addWidget(self.label_31)
        self.label_30 = QtGui.QLabel(self.S5_Tipo)
        self.label_30.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_16.addWidget(self.label_30)
        self.verticalLayout_17.addLayout(self.verticalLayout_16)
        self.Grade_horario.addWidget(self.S5_Tipo, 7, 1, 1, 1)
        self.S4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S4_Tipo.sizePolicy().hasHeightForWidth())
        self.S4_Tipo.setSizePolicy(sizePolicy)
        self.S4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S4_Tipo.setCheckable(False)
        self.S4_Tipo.setObjectName("S4_Tipo")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.S4_Tipo)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_28 = QtGui.QLabel(self.S4_Tipo)
        self.label_28.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.verticalLayout_14.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.S4_Tipo)
        self.label_29.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_29.setAlignment(QtCore.Qt.AlignCenter)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_14.addWidget(self.label_29)
        self.verticalLayout_15.addLayout(self.verticalLayout_14)
        self.Grade_horario.addWidget(self.S4_Tipo, 6, 1, 1, 1)
        self.T6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T6_Tipo.sizePolicy().hasHeightForWidth())
        self.T6_Tipo.setSizePolicy(sizePolicy)
        self.T6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T6_Tipo.setObjectName("T6_Tipo")
        self.verticalLayout_48 = QtGui.QVBoxLayout(self.T6_Tipo)
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.verticalLayout_47 = QtGui.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_38 = QtGui.QLabel(self.T6_Tipo)
        self.label_38.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_47.addWidget(self.label_38)
        self.label_40 = QtGui.QLabel(self.T6_Tipo)
        self.label_40.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_47.addWidget(self.label_40)
        self.verticalLayout_48.addLayout(self.verticalLayout_47)
        self.Grade_horario.addWidget(self.T6_Tipo, 8, 2, 1, 1)
        self.Qi5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi5_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi5_Tipo.setSizePolicy(sizePolicy)
        self.Qi5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi5_Tipo.setObjectName("Qi5_Tipo")
        self.verticalLayout_66 = QtGui.QVBoxLayout(self.Qi5_Tipo)
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.verticalLayout_65 = QtGui.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.label_58 = QtGui.QLabel(self.Qi5_Tipo)
        self.label_58.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_58.setAlignment(QtCore.Qt.AlignCenter)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_65.addWidget(self.label_58)
        self.label_57 = QtGui.QLabel(self.Qi5_Tipo)
        self.label_57.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_57.setAlignment(QtCore.Qt.AlignCenter)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_65.addWidget(self.label_57)
        self.verticalLayout_66.addLayout(self.verticalLayout_65)
        self.Grade_horario.addWidget(self.Qi5_Tipo, 7, 4, 1, 1)
        self.Q5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q5_Tipo.sizePolicy().hasHeightForWidth())
        self.Q5_Tipo.setSizePolicy(sizePolicy)
        self.Q5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q5_Tipo.setObjectName("Q5_Tipo")
        self.verticalLayout_52 = QtGui.QVBoxLayout(self.Q5_Tipo)
        self.verticalLayout_52.setObjectName("verticalLayout_52")
        self.verticalLayout_51 = QtGui.QVBoxLayout()
        self.verticalLayout_51.setObjectName("verticalLayout_51")
        self.label_54 = QtGui.QLabel(self.Q5_Tipo)
        self.label_54.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_51.addWidget(self.label_54)
        self.label_55 = QtGui.QLabel(self.Q5_Tipo)
        self.label_55.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_55.setAlignment(QtCore.Qt.AlignCenter)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_51.addWidget(self.label_55)
        self.verticalLayout_52.addLayout(self.verticalLayout_51)
        self.Grade_horario.addWidget(self.Q5_Tipo, 7, 3, 1, 1)
        self.Q4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q4_Tipo.sizePolicy().hasHeightForWidth())
        self.Q4_Tipo.setSizePolicy(sizePolicy)
        self.Q4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q4_Tipo.setObjectName("Q4_Tipo")
        self.verticalLayout_54 = QtGui.QVBoxLayout(self.Q4_Tipo)
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.verticalLayout_53 = QtGui.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.label_53 = QtGui.QLabel(self.Q4_Tipo)
        self.label_53.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setObjectName("label_53")
        self.verticalLayout_53.addWidget(self.label_53)
        self.label_52 = QtGui.QLabel(self.Q4_Tipo)
        self.label_52.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_52.setAlignment(QtCore.Qt.AlignCenter)
        self.label_52.setObjectName("label_52")
        self.verticalLayout_53.addWidget(self.label_52)
        self.verticalLayout_54.addLayout(self.verticalLayout_53)
        self.Grade_horario.addWidget(self.Q4_Tipo, 6, 3, 1, 1)
        self.Q6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q6_Tipo.sizePolicy().hasHeightForWidth())
        self.Q6_Tipo.setSizePolicy(sizePolicy)
        self.Q6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q6_Tipo.setObjectName("Q6_Tipo")
        self.verticalLayout_78 = QtGui.QVBoxLayout(self.Q6_Tipo)
        self.verticalLayout_78.setObjectName("verticalLayout_78")
        self.verticalLayout_77 = QtGui.QVBoxLayout()
        self.verticalLayout_77.setObjectName("verticalLayout_77")
        self.label_56 = QtGui.QLabel(self.Q6_Tipo)
        self.label_56.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_56.setAlignment(QtCore.Qt.AlignCenter)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_77.addWidget(self.label_56)
        self.label_66 = QtGui.QLabel(self.Q6_Tipo)
        self.label_66.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_66.setAlignment(QtCore.Qt.AlignCenter)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_77.addWidget(self.label_66)
        self.verticalLayout_78.addLayout(self.verticalLayout_77)
        self.Grade_horario.addWidget(self.Q6_Tipo, 8, 3, 1, 1)
        self.Qi4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi4_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi4_Tipo.setSizePolicy(sizePolicy)
        self.Qi4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi4_Tipo.setObjectName("Qi4_Tipo")
        self.verticalLayout_68 = QtGui.QVBoxLayout(self.Qi4_Tipo)
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.verticalLayout_67 = QtGui.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.label_59 = QtGui.QLabel(self.Qi4_Tipo)
        self.label_59.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_59.setAlignment(QtCore.Qt.AlignCenter)
        self.label_59.setObjectName("label_59")
        self.verticalLayout_67.addWidget(self.label_59)
        self.label_80 = QtGui.QLabel(self.Qi4_Tipo)
        self.label_80.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_80.setAlignment(QtCore.Qt.AlignCenter)
        self.label_80.setObjectName("label_80")
        self.verticalLayout_67.addWidget(self.label_80)
        self.verticalLayout_68.addLayout(self.verticalLayout_67)
        self.Grade_horario.addWidget(self.Qi4_Tipo, 6, 4, 1, 1)
        self.T4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T4_Tipo.sizePolicy().hasHeightForWidth())
        self.T4_Tipo.setSizePolicy(sizePolicy)
        self.T4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T4_Tipo.setObjectName("T4_Tipo")
        self.verticalLayout_44 = QtGui.QVBoxLayout(self.T4_Tipo)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.verticalLayout_43 = QtGui.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_45 = QtGui.QLabel(self.T4_Tipo)
        self.label_45.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_45.setAlignment(QtCore.Qt.AlignCenter)
        self.label_45.setObjectName("label_45")
        self.verticalLayout_43.addWidget(self.label_45)
        self.label_41 = QtGui.QLabel(self.T4_Tipo)
        self.label_41.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_43.addWidget(self.label_41)
        self.verticalLayout_44.addLayout(self.verticalLayout_43)
        self.Grade_horario.addWidget(self.T4_Tipo, 6, 2, 1, 1)
        self.Q7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q7_Tipo.sizePolicy().hasHeightForWidth())
        self.Q7_Tipo.setSizePolicy(sizePolicy)
        self.Q7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q7_Tipo.setObjectName("Q7_Tipo")
        self.verticalLayout_76 = QtGui.QVBoxLayout(self.Q7_Tipo)
        self.verticalLayout_76.setObjectName("verticalLayout_76")
        self.verticalLayout_75 = QtGui.QVBoxLayout()
        self.verticalLayout_75.setObjectName("verticalLayout_75")
        self.label_64 = QtGui.QLabel(self.Q7_Tipo)
        self.label_64.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_64.setAlignment(QtCore.Qt.AlignCenter)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_75.addWidget(self.label_64)
        self.label_65 = QtGui.QLabel(self.Q7_Tipo)
        self.label_65.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_65.setAlignment(QtCore.Qt.AlignCenter)
        self.label_65.setObjectName("label_65")
        self.verticalLayout_75.addWidget(self.label_65)
        self.verticalLayout_76.addLayout(self.verticalLayout_75)
        self.Grade_horario.addWidget(self.Q7_Tipo, 9, 3, 1, 1)
        self.Sx4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx4_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx4_Tipo.setSizePolicy(sizePolicy)
        self.Sx4_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx4_Tipo.setObjectName("Sx4_Tipo")
        self.verticalLayout_70 = QtGui.QVBoxLayout(self.Sx4_Tipo)
        self.verticalLayout_70.setObjectName("verticalLayout_70")
        self.verticalLayout_69 = QtGui.QVBoxLayout()
        self.verticalLayout_69.setObjectName("verticalLayout_69")
        self.label_77 = QtGui.QLabel(self.Sx4_Tipo)
        self.label_77.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_77.setAlignment(QtCore.Qt.AlignCenter)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_69.addWidget(self.label_77)
        self.label_78 = QtGui.QLabel(self.Sx4_Tipo)
        self.label_78.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_78.setAlignment(QtCore.Qt.AlignCenter)
        self.label_78.setObjectName("label_78")
        self.verticalLayout_69.addWidget(self.label_78)
        self.verticalLayout_70.addLayout(self.verticalLayout_69)
        self.Grade_horario.addWidget(self.Sx4_Tipo, 6, 5, 1, 1)
        self.Sx3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx3_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx3_Tipo.setSizePolicy(sizePolicy)
        self.Sx3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx3_Tipo.setObjectName("Sx3_Tipo")
        self.verticalLayout_58 = QtGui.QVBoxLayout(self.Sx3_Tipo)
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.verticalLayout_57 = QtGui.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.label_79 = QtGui.QLabel(self.Sx3_Tipo)
        self.label_79.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_79.setAlignment(QtCore.Qt.AlignCenter)
        self.label_79.setObjectName("label_79")
        self.verticalLayout_57.addWidget(self.label_79)
        self.label_85 = QtGui.QLabel(self.Sx3_Tipo)
        self.label_85.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_85.setAlignment(QtCore.Qt.AlignCenter)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_57.addWidget(self.label_85)
        self.verticalLayout_58.addLayout(self.verticalLayout_57)
        self.Grade_horario.addWidget(self.Sx3_Tipo, 5, 5, 1, 1)
        self.Qi6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi6_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi6_Tipo.setSizePolicy(sizePolicy)
        self.Qi6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi6_Tipo.setObjectName("Qi6_Tipo")
        self.verticalLayout_80 = QtGui.QVBoxLayout(self.Qi6_Tipo)
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.verticalLayout_79 = QtGui.QVBoxLayout()
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.label_68 = QtGui.QLabel(self.Qi6_Tipo)
        self.label_68.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_68.setAlignment(QtCore.Qt.AlignCenter)
        self.label_68.setObjectName("label_68")
        self.verticalLayout_79.addWidget(self.label_68)
        self.label_67 = QtGui.QLabel(self.Qi6_Tipo)
        self.label_67.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_67.setAlignment(QtCore.Qt.AlignCenter)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_79.addWidget(self.label_67)
        self.verticalLayout_80.addLayout(self.verticalLayout_79)
        self.Grade_horario.addWidget(self.Qi6_Tipo, 8, 4, 1, 1)
        self.D4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D4_Tipo.sizePolicy().hasHeightForWidth())
        self.D4_Tipo.setSizePolicy(sizePolicy)
        self.D4_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D4_Tipo.setObjectName("D4_Tipo")
        self.verticalLayout_96 = QtGui.QVBoxLayout(self.D4_Tipo)
        self.verticalLayout_96.setObjectName("verticalLayout_96")
        self.verticalLayout_95 = QtGui.QVBoxLayout()
        self.verticalLayout_95.setObjectName("verticalLayout_95")
        self.label_98 = QtGui.QLabel(self.D4_Tipo)
        self.label_98.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_98.setAlignment(QtCore.Qt.AlignCenter)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_95.addWidget(self.label_98)
        self.verticalLayout_96.addLayout(self.verticalLayout_95)
        self.Grade_horario.addWidget(self.D4_Tipo, 6, 7, 1, 1)
        self.Sx7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx7_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx7_Tipo.setSizePolicy(sizePolicy)
        self.Sx7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx7_Tipo.setObjectName("Sx7_Tipo")
        self.verticalLayout_86 = QtGui.QVBoxLayout(self.Sx7_Tipo)
        self.verticalLayout_86.setObjectName("verticalLayout_86")
        self.verticalLayout_85 = QtGui.QVBoxLayout()
        self.verticalLayout_85.setObjectName("verticalLayout_85")
        self.label_75 = QtGui.QLabel(self.Sx7_Tipo)
        self.label_75.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_75.setAlignment(QtCore.Qt.AlignCenter)
        self.label_75.setObjectName("label_75")
        self.verticalLayout_85.addWidget(self.label_75)
        self.label_76 = QtGui.QLabel(self.Sx7_Tipo)
        self.label_76.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_76.setAlignment(QtCore.Qt.AlignCenter)
        self.label_76.setObjectName("label_76")
        self.verticalLayout_85.addWidget(self.label_76)
        self.verticalLayout_86.addLayout(self.verticalLayout_85)
        self.Grade_horario.addWidget(self.Sx7_Tipo, 9, 5, 1, 1)
        self.Sx6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx6_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx6_Tipo.setSizePolicy(sizePolicy)
        self.Sx6_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx6_Tipo.setObjectName("Sx6_Tipo")
        self.verticalLayout_82 = QtGui.QVBoxLayout(self.Sx6_Tipo)
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.verticalLayout_81 = QtGui.QVBoxLayout()
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.label_73 = QtGui.QLabel(self.Sx6_Tipo)
        self.label_73.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_73.setAlignment(QtCore.Qt.AlignCenter)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_81.addWidget(self.label_73)
        self.label_74 = QtGui.QLabel(self.Sx6_Tipo)
        self.label_74.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_74.setAlignment(QtCore.Qt.AlignCenter)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_81.addWidget(self.label_74)
        self.verticalLayout_82.addLayout(self.verticalLayout_81)
        self.Grade_horario.addWidget(self.Sx6_Tipo, 8, 5, 1, 1)
        self.Qi7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi7_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi7_Tipo.setSizePolicy(sizePolicy)
        self.Qi7_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi7_Tipo.setObjectName("Qi7_Tipo")
        self.verticalLayout_84 = QtGui.QVBoxLayout(self.Qi7_Tipo)
        self.verticalLayout_84.setObjectName("verticalLayout_84")
        self.verticalLayout_83 = QtGui.QVBoxLayout()
        self.verticalLayout_83.setObjectName("verticalLayout_83")
        self.label_69 = QtGui.QLabel(self.Qi7_Tipo)
        self.label_69.setAlignment(QtCore.Qt.AlignCenter)
        self.label_69.setObjectName("label_69")
        self.verticalLayout_83.addWidget(self.label_69)
        self.label_70 = QtGui.QLabel(self.Qi7_Tipo)
        self.label_70.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_70.setAlignment(QtCore.Qt.AlignCenter)
        self.label_70.setObjectName("label_70")
        self.verticalLayout_83.addWidget(self.label_70)
        self.verticalLayout_84.addLayout(self.verticalLayout_83)
        self.Grade_horario.addWidget(self.Qi7_Tipo, 9, 4, 1, 1)
        self.Sx5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx5_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx5_Tipo.setSizePolicy(sizePolicy)
        self.Sx5_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx5_Tipo.setObjectName("Sx5_Tipo")
        self.verticalLayout_74 = QtGui.QVBoxLayout(self.Sx5_Tipo)
        self.verticalLayout_74.setObjectName("verticalLayout_74")
        self.verticalLayout_73 = QtGui.QVBoxLayout()
        self.verticalLayout_73.setObjectName("verticalLayout_73")
        self.label_72 = QtGui.QLabel(self.Sx5_Tipo)
        self.label_72.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_72.setAlignment(QtCore.Qt.AlignCenter)
        self.label_72.setObjectName("label_72")
        self.verticalLayout_73.addWidget(self.label_72)
        self.label_71 = QtGui.QLabel(self.Sx5_Tipo)
        self.label_71.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_71.setAlignment(QtCore.Qt.AlignCenter)
        self.label_71.setObjectName("label_71")
        self.verticalLayout_73.addWidget(self.label_71)
        self.verticalLayout_74.addLayout(self.verticalLayout_73)
        self.Grade_horario.addWidget(self.Sx5_Tipo, 7, 5, 1, 1)
        self.D6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D6_Tipo.sizePolicy().hasHeightForWidth())
        self.D6_Tipo.setSizePolicy(sizePolicy)
        self.D6_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D6_Tipo.setObjectName("D6_Tipo")
        self.verticalLayout_100 = QtGui.QVBoxLayout(self.D6_Tipo)
        self.verticalLayout_100.setObjectName("verticalLayout_100")
        self.verticalLayout_99 = QtGui.QVBoxLayout()
        self.verticalLayout_99.setObjectName("verticalLayout_99")
        self.label_96 = QtGui.QLabel(self.D6_Tipo)
        self.label_96.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_96.setAlignment(QtCore.Qt.AlignCenter)
        self.label_96.setObjectName("label_96")
        self.verticalLayout_99.addWidget(self.label_96)
        self.verticalLayout_100.addLayout(self.verticalLayout_99)
        self.Grade_horario.addWidget(self.D6_Tipo, 8, 7, 1, 1)
        self.D5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D5_Tipo.sizePolicy().hasHeightForWidth())
        self.D5_Tipo.setSizePolicy(sizePolicy)
        self.D5_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D5_Tipo.setObjectName("D5_Tipo")
        self.verticalLayout_94 = QtGui.QVBoxLayout(self.D5_Tipo)
        self.verticalLayout_94.setObjectName("verticalLayout_94")
        self.verticalLayout_93 = QtGui.QVBoxLayout()
        self.verticalLayout_93.setObjectName("verticalLayout_93")
        self.label_97 = QtGui.QLabel(self.D5_Tipo)
        self.label_97.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_97.setAlignment(QtCore.Qt.AlignCenter)
        self.label_97.setObjectName("label_97")
        self.verticalLayout_93.addWidget(self.label_97)
        self.verticalLayout_94.addLayout(self.verticalLayout_93)
        self.Grade_horario.addWidget(self.D5_Tipo, 7, 7, 1, 1)
        self.Sa4_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa4_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa4_Tipo.setSizePolicy(sizePolicy)
        self.Sa4_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa4_Tipo.setObjectName("Sa4_Tipo")
        self.verticalLayout_72 = QtGui.QVBoxLayout(self.Sa4_Tipo)
        self.verticalLayout_72.setObjectName("verticalLayout_72")
        self.verticalLayout_71 = QtGui.QVBoxLayout()
        self.verticalLayout_71.setObjectName("verticalLayout_71")
        self.label_86 = QtGui.QLabel(self.Sa4_Tipo)
        self.label_86.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_86.setAlignment(QtCore.Qt.AlignCenter)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_71.addWidget(self.label_86)
        self.verticalLayout_72.addLayout(self.verticalLayout_71)
        self.Grade_horario.addWidget(self.Sa4_Tipo, 6, 6, 1, 1)
        self.Sa5_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa5_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa5_Tipo.setSizePolicy(sizePolicy)
        self.Sa5_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa5_Tipo.setObjectName("Sa5_Tipo")
        self.verticalLayout_92 = QtGui.QVBoxLayout(self.Sa5_Tipo)
        self.verticalLayout_92.setObjectName("verticalLayout_92")
        self.verticalLayout_91 = QtGui.QVBoxLayout()
        self.verticalLayout_91.setObjectName("verticalLayout_91")
        self.label_92 = QtGui.QLabel(self.Sa5_Tipo)
        self.label_92.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_92.setAlignment(QtCore.Qt.AlignCenter)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_91.addWidget(self.label_92)
        self.verticalLayout_92.addLayout(self.verticalLayout_91)
        self.Grade_horario.addWidget(self.Sa5_Tipo, 7, 6, 1, 1)
        self.Sa7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa7_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa7_Tipo.setSizePolicy(sizePolicy)
        self.Sa7_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa7_Tipo.setObjectName("Sa7_Tipo")
        self.verticalLayout_88 = QtGui.QVBoxLayout(self.Sa7_Tipo)
        self.verticalLayout_88.setObjectName("verticalLayout_88")
        self.verticalLayout_87 = QtGui.QVBoxLayout()
        self.verticalLayout_87.setObjectName("verticalLayout_87")
        self.label_94 = QtGui.QLabel(self.Sa7_Tipo)
        self.label_94.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_94.setAlignment(QtCore.Qt.AlignCenter)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_87.addWidget(self.label_94)
        self.verticalLayout_88.addLayout(self.verticalLayout_87)
        self.Grade_horario.addWidget(self.Sa7_Tipo, 9, 6, 1, 1)
        self.D7_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.D7_Tipo.sizePolicy().hasHeightForWidth())
        self.D7_Tipo.setSizePolicy(sizePolicy)
        self.D7_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.D7_Tipo.setObjectName("D7_Tipo")
        self.verticalLayout_98 = QtGui.QVBoxLayout(self.D7_Tipo)
        self.verticalLayout_98.setObjectName("verticalLayout_98")
        self.verticalLayout_97 = QtGui.QVBoxLayout()
        self.verticalLayout_97.setObjectName("verticalLayout_97")
        self.label_95 = QtGui.QLabel(self.D7_Tipo)
        self.label_95.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_95.setAlignment(QtCore.Qt.AlignCenter)
        self.label_95.setObjectName("label_95")
        self.verticalLayout_97.addWidget(self.label_95)
        self.verticalLayout_98.addLayout(self.verticalLayout_97)
        self.Grade_horario.addWidget(self.D7_Tipo, 9, 7, 1, 1)
        self.Sa6_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sa6_Tipo.sizePolicy().hasHeightForWidth())
        self.Sa6_Tipo.setSizePolicy(sizePolicy)
        self.Sa6_Tipo.setMinimumSize(QtCore.QSize(100, 100))
        self.Sa6_Tipo.setObjectName("Sa6_Tipo")
        self.verticalLayout_90 = QtGui.QVBoxLayout(self.Sa6_Tipo)
        self.verticalLayout_90.setObjectName("verticalLayout_90")
        self.verticalLayout_89 = QtGui.QVBoxLayout()
        self.verticalLayout_89.setObjectName("verticalLayout_89")
        self.label_93 = QtGui.QLabel(self.Sa6_Tipo)
        self.label_93.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_93.setAlignment(QtCore.Qt.AlignCenter)
        self.label_93.setObjectName("label_93")
        self.verticalLayout_89.addWidget(self.label_93)
        self.verticalLayout_90.addLayout(self.verticalLayout_89)
        self.Grade_horario.addWidget(self.Sa6_Tipo, 8, 6, 1, 1)
        self.Sx2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx2_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx2_Tipo.setSizePolicy(sizePolicy)
        self.Sx2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx2_Tipo.setObjectName("Sx2_Tipo")
        self.verticalLayout_36 = QtGui.QVBoxLayout(self.Sx2_Tipo)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.verticalLayout_35 = QtGui.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_83 = QtGui.QLabel(self.Sx2_Tipo)
        self.label_83.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_83.setAlignment(QtCore.Qt.AlignCenter)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_35.addWidget(self.label_83)
        self.label_84 = QtGui.QLabel(self.Sx2_Tipo)
        self.label_84.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_84.setAlignment(QtCore.Qt.AlignCenter)
        self.label_84.setObjectName("label_84")
        self.verticalLayout_35.addWidget(self.label_84)
        self.verticalLayout_36.addLayout(self.verticalLayout_35)
        self.Grade_horario.addWidget(self.Sx2_Tipo, 4, 5, 1, 1)
        self.Sx1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sx1_Tipo.sizePolicy().hasHeightForWidth())
        self.Sx1_Tipo.setSizePolicy(sizePolicy)
        self.Sx1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Sx1_Tipo.setObjectName("Sx1_Tipo")
        self.verticalLayout_34 = QtGui.QVBoxLayout(self.Sx1_Tipo)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.verticalLayout_33 = QtGui.QVBoxLayout()
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        self.label_81 = QtGui.QLabel(self.Sx1_Tipo)
        self.label_81.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_81.setAlignment(QtCore.Qt.AlignCenter)
        self.label_81.setObjectName("label_81")
        self.verticalLayout_33.addWidget(self.label_81)
        self.label_82 = QtGui.QLabel(self.Sx1_Tipo)
        self.label_82.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_82.setAlignment(QtCore.Qt.AlignCenter)
        self.label_82.setObjectName("label_82")
        self.verticalLayout_33.addWidget(self.label_82)
        self.verticalLayout_34.addLayout(self.verticalLayout_33)
        self.Grade_horario.addWidget(self.Sx1_Tipo, 3, 5, 1, 1)
        self.Qi1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi1_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi1_Tipo.setSizePolicy(sizePolicy)
        self.Qi1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi1_Tipo.setObjectName("Qi1_Tipo")
        self.verticalLayout_32 = QtGui.QVBoxLayout(self.Qi1_Tipo)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.verticalLayout_31 = QtGui.QVBoxLayout()
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.label_60 = QtGui.QLabel(self.Qi1_Tipo)
        self.label_60.setObjectName("label_60")
        self.verticalLayout_31.addWidget(self.label_60)
        self.label_63 = QtGui.QLabel(self.Qi1_Tipo)
        self.label_63.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_63.setAlignment(QtCore.Qt.AlignCenter)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_31.addWidget(self.label_63)
        self.verticalLayout_32.addLayout(self.verticalLayout_31)
        self.Grade_horario.addWidget(self.Qi1_Tipo, 3, 4, 1, 1)
        self.T1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T1_Tipo.sizePolicy().hasHeightForWidth())
        self.T1_Tipo.setSizePolicy(sizePolicy)
        self.T1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T1_Tipo.setObjectName("T1_Tipo")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.T1_Tipo)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.T1_Labels = QtGui.QVBoxLayout()
        self.T1_Labels.setObjectName("T1_Labels")
        self.T1_Aula = QtGui.QLabel(self.T1_Tipo)
        self.T1_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.T1_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.T1_Aula.setObjectName("T1_Aula")
        self.T1_Labels.addWidget(self.T1_Aula)
        self.T1_Sala = QtGui.QLabel(self.T1_Tipo)
        self.T1_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.T1_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.T1_Sala.setObjectName("T1_Sala")
        self.T1_Labels.addWidget(self.T1_Sala)
        self.verticalLayout_9.addLayout(self.T1_Labels)
        self.Grade_horario.addWidget(self.T1_Tipo, 3, 2, 1, 1)
        self.Q1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q1_Tipo.sizePolicy().hasHeightForWidth())
        self.Q1_Tipo.setSizePolicy(sizePolicy)
        self.Q1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q1_Tipo.setObjectName("Q1_Tipo")
        self.verticalLayout_11 = QtGui.QVBoxLayout(self.Q1_Tipo)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_18 = QtGui.QLabel(self.Q1_Tipo)
        self.label_18.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_10.addWidget(self.label_18)
        self.label_17 = QtGui.QLabel(self.Q1_Tipo)
        self.label_17.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.verticalLayout_11.addLayout(self.verticalLayout_10)
        self.Grade_horario.addWidget(self.Q1_Tipo, 3, 3, 1, 1)
        self.S2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S2_Tipo.sizePolicy().hasHeightForWidth())
        self.S2_Tipo.setSizePolicy(sizePolicy)
        self.S2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S2_Tipo.setCheckable(False)
        self.S2_Tipo.setObjectName("S2_Tipo")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.S2_Tipo)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.S2_Labels = QtGui.QVBoxLayout()
        self.S2_Labels.setObjectName("S2_Labels")
        self.S2_Aula = QtGui.QLabel(self.S2_Tipo)
        self.S2_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.S2_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.S2_Aula.setObjectName("S2_Aula")
        self.S2_Labels.addWidget(self.S2_Aula)
        self.S2_Sala = QtGui.QLabel(self.S2_Tipo)
        self.S2_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.S2_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.S2_Sala.setObjectName("S2_Sala")
        self.S2_Labels.addWidget(self.S2_Sala)
        self.verticalLayout_5.addLayout(self.S2_Labels)
        self.Grade_horario.addWidget(self.S2_Tipo, 4, 1, 1, 1)
        self.S1_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S1_Tipo.sizePolicy().hasHeightForWidth())
        self.S1_Tipo.setSizePolicy(sizePolicy)
        self.S1_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S1_Tipo.setCheckable(False)
        self.S1_Tipo.setObjectName("S1_Tipo")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.S1_Tipo)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.S1_Labels = QtGui.QVBoxLayout()
        self.S1_Labels.setObjectName("S1_Labels")
        self.S1_Aula = QtGui.QLabel(self.S1_Tipo)
        self.S1_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.S1_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.S1_Aula.setObjectName("S1_Aula")
        self.S1_Labels.addWidget(self.S1_Aula)
        self.S1_Sala = QtGui.QLabel(self.S1_Tipo)
        self.S1_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.S1_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.S1_Sala.setObjectName("S1_Sala")
        self.S1_Labels.addWidget(self.S1_Sala)
        self.verticalLayout_7.addLayout(self.S1_Labels)
        self.Grade_horario.addWidget(self.S1_Tipo, 3, 1, 1, 1)
        self.S3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.S3_Tipo.sizePolicy().hasHeightForWidth())
        self.S3_Tipo.setSizePolicy(sizePolicy)
        self.S3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.S3_Tipo.setCheckable(False)
        self.S3_Tipo.setObjectName("S3_Tipo")
        self.verticalLayout_13 = QtGui.QVBoxLayout(self.S3_Tipo)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.S3_Labels = QtGui.QVBoxLayout()
        self.S3_Labels.setObjectName("S3_Labels")
        self.S3_Aula = QtGui.QLabel(self.S3_Tipo)
        self.S3_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.S3_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.S3_Aula.setObjectName("S3_Aula")
        self.S3_Labels.addWidget(self.S3_Aula)
        self.S3_Sala = QtGui.QLabel(self.S3_Tipo)
        self.S3_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.S3_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.S3_Sala.setObjectName("S3_Sala")
        self.S3_Labels.addWidget(self.S3_Sala)
        self.verticalLayout_13.addLayout(self.S3_Labels)
        self.Grade_horario.addWidget(self.S3_Tipo, 5, 1, 1, 1)
        self.Qi2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Qi2_Tipo.sizePolicy().hasHeightForWidth())
        self.Qi2_Tipo.setSizePolicy(sizePolicy)
        self.Qi2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Qi2_Tipo.setObjectName("Qi2_Tipo")
        self.verticalLayout_30 = QtGui.QVBoxLayout(self.Qi2_Tipo)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.verticalLayout_29 = QtGui.QVBoxLayout()
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label_61 = QtGui.QLabel(self.Qi2_Tipo)
        self.label_61.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_61.setAlignment(QtCore.Qt.AlignCenter)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_29.addWidget(self.label_61)
        self.label_62 = QtGui.QLabel(self.Qi2_Tipo)
        self.label_62.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_62.setAlignment(QtCore.Qt.AlignCenter)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_29.addWidget(self.label_62)
        self.verticalLayout_30.addLayout(self.verticalLayout_29)
        self.Grade_horario.addWidget(self.Qi2_Tipo, 4, 4, 1, 1)
        self.Q2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Q2_Tipo.sizePolicy().hasHeightForWidth())
        self.Q2_Tipo.setSizePolicy(sizePolicy)
        self.Q2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.Q2_Tipo.setObjectName("Q2_Tipo")
        self.verticalLayout_28 = QtGui.QVBoxLayout(self.Q2_Tipo)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.verticalLayout_27 = QtGui.QVBoxLayout()
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_48 = QtGui.QLabel(self.Q2_Tipo)
        self.label_48.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_48.setAlignment(QtCore.Qt.AlignCenter)
        self.label_48.setObjectName("label_48")
        self.verticalLayout_27.addWidget(self.label_48)
        self.label_49 = QtGui.QLabel(self.Q2_Tipo)
        self.label_49.setFrameShape(QtGui.QFrame.NoFrame)
        self.label_49.setAlignment(QtCore.Qt.AlignCenter)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_27.addWidget(self.label_49)
        self.verticalLayout_28.addLayout(self.verticalLayout_27)
        self.Grade_horario.addWidget(self.Q2_Tipo, 4, 3, 1, 1)
        self.T2_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T2_Tipo.sizePolicy().hasHeightForWidth())
        self.T2_Tipo.setSizePolicy(sizePolicy)
        self.T2_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T2_Tipo.setObjectName("T2_Tipo")
        self.verticalLayout_24 = QtGui.QVBoxLayout(self.T2_Tipo)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.T2_Labels = QtGui.QVBoxLayout()
        self.T2_Labels.setObjectName("T2_Labels")
        self.T2_Aula = QtGui.QLabel(self.T2_Tipo)
        self.T2_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.T2_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.T2_Aula.setObjectName("T2_Aula")
        self.T2_Labels.addWidget(self.T2_Aula)
        self.T2_Sala = QtGui.QLabel(self.T2_Tipo)
        self.T2_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.T2_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.T2_Sala.setObjectName("T2_Sala")
        self.T2_Labels.addWidget(self.T2_Sala)
        self.verticalLayout_24.addLayout(self.T2_Labels)
        self.Grade_horario.addWidget(self.T2_Tipo, 4, 2, 1, 1)
        self.T3_Tipo = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T3_Tipo.sizePolicy().hasHeightForWidth())
        self.T3_Tipo.setSizePolicy(sizePolicy)
        self.T3_Tipo.setMinimumSize(QtCore.QSize(160, 100))
        self.T3_Tipo.setObjectName("T3_Tipo")
        self.verticalLayout_26 = QtGui.QVBoxLayout(self.T3_Tipo)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.T3_Labels = QtGui.QVBoxLayout()
        self.T3_Labels.setObjectName("T3_Labels")
        self.T3_Aula = QtGui.QLabel(self.T3_Tipo)
        self.T3_Aula.setFrameShape(QtGui.QFrame.NoFrame)
        self.T3_Aula.setAlignment(QtCore.Qt.AlignCenter)
        self.T3_Aula.setObjectName("T3_Aula")
        self.T3_Labels.addWidget(self.T3_Aula)
        self.T3_Sala = QtGui.QLabel(self.T3_Tipo)
        self.T3_Sala.setFrameShape(QtGui.QFrame.NoFrame)
        self.T3_Sala.setAlignment(QtCore.Qt.AlignCenter)
        self.T3_Sala.setObjectName("T3_Sala")
        self.T3_Labels.addWidget(self.T3_Sala)
        self.verticalLayout_26.addLayout(self.T3_Labels)
        self.Grade_horario.addWidget(self.T3_Tipo, 5, 2, 1, 1)
        self.Label_Horarios = QtGui.QLabel(self.centralwidget)
        self.Label_Horarios.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Label_Horarios.setFont(font)
        self.Label_Horarios.setFrameShape(QtGui.QFrame.Box)
        self.Label_Horarios.setFrameShadow(QtGui.QFrame.Plain)
        self.Label_Horarios.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_Horarios.setObjectName("Label_Horarios")
        self.Grade_horario.addWidget(self.Label_Horarios, 0, 0, 1, 1)
        self.horizontalLayout.addLayout(self.Grade_horario)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("MainWindow", "Calendário Semanal"))
        self.Label_TituloJanela.setText(_translate("MainWindow", "Calendário Semanal da Sala"))
        self.checkBox_2.setText(_translate("MainWindow", "Editar Aulas"))
        self.checkBox.setText(_translate("MainWindow", "Editar Horários"))
        self.D3_Tipo.setTitle(_translate("MainWindow", "Horário 3"))
        self.label_99.setText(_translate("MainWindow", "-"))
        self.D1_Tipo.setTitle(_translate("MainWindow", "Horário 1"))
        self.label_90.setText(_translate("MainWindow", "-"))
        self.Sa1_Tipo.setTitle(_translate("MainWindow", "Horário 1"))
        self.label_89.setText(_translate("MainWindow", "-"))
        self.Sa3_Tipo.setTitle(_translate("MainWindow", "Horário 3"))
        self.label_87.setText(_translate("MainWindow", "-"))
        self.Sa2_Tipo.setTitle(_translate("MainWindow", "Horário 2"))
        self.label_88.setText(_translate("MainWindow", "-"))
        self.Label_Domingo.setText(_translate("MainWindow", "Domingo"))
        self.Label_Horario7.setText(_translate("MainWindow", "20h15 - 22h15"))
        self.Label_Horario5.setText(_translate("MainWindow", "15h45 - 17h45"))
        self.Label_Quarta.setText(_translate("MainWindow", "Quarta-feira"))
        self.Label_Quinta.setText(_translate("MainWindow", "Quinta-feira"))
        self.Qi3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.label.setText(_translate("MainWindow", "-"))
        self.label_2.setText(_translate("MainWindow", "-"))
        self.Label_Horario3.setText(_translate("MainWindow", "11h45 - 13h30"))
        self.Label_Sabado.setText(_translate("MainWindow", "Sábado"))
        self.Label_Sexta.setText(_translate("MainWindow", "Sexta-feira"))
        self.Label_Horario6.setText(_translate("MainWindow", "18h00 - 20h00"))
        self.Label_Terca.setText(_translate("MainWindow", "Terça-feira"))
        self.Label_Horario4.setText(_translate("MainWindow", "13h30 - 15h30"))
        self.Label_Horario2.setText(_translate("MainWindow", "09h45 - 11h45"))
        self.Q3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.Q3_Aula.setText(_translate("MainWindow", "-"))
        self.Q3_Sala.setText(_translate("MainWindow", "-"))
        self.D2_Tipo.setTitle(_translate("MainWindow", "Horário 2"))
        self.label_91.setText(_translate("MainWindow", "-"))
        self.Label_Segunda.setText(_translate("MainWindow", "Segunda-feira"))
        self.Label_Horario1.setText(_translate("MainWindow", "07h30 - 09h30"))
        self.T7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_37.setText(_translate("MainWindow", "-"))
        self.label_36.setText(_translate("MainWindow", "-"))
        self.S7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_34.setText(_translate("MainWindow", "-"))
        self.label_35.setText(_translate("MainWindow", "-"))
        self.T5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_39.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Instrumentação </span></p><p align=\"center\"><span style=\" font-weight:600;\">e Medição</span></p></body></html>"))
        self.label_42.setText(_translate("MainWindow", "Sala 401"))
        self.S6_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_32.setText(_translate("MainWindow", "-"))
        self.label_33.setText(_translate("MainWindow", "-"))
        self.S5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_31.setText(_translate("MainWindow", "-"))
        self.label_30.setText(_translate("MainWindow", "-"))
        self.S4_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação</span></p><p align=\"center\"><span style=\" font-weight:600;\"> do Mundo Físico</span></p></body></html>"))
        self.label_29.setText(_translate("MainWindow", "Sala 403"))
        self.T6_Tipo.setTitle(_translate("MainWindow", "Aula 5"))
        self.label_38.setText(_translate("MainWindow", "-"))
        self.label_40.setText(_translate("MainWindow", "-"))
        self.Qi5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_58.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação </span></p><p align=\"center\"><span style=\" font-weight:600;\">do Mundo Físico</span></p></body></html>"))
        self.label_57.setText(_translate("MainWindow", "Sala 403"))
        self.Q5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_54.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Natureza do Design</span></p></body></html>"))
        self.label_55.setText(_translate("MainWindow", "Sala 403"))
        self.Q4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_53.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Natureza do Design</span></p></body></html>"))
        self.label_52.setText(_translate("MainWindow", "Sala 403"))
        self.Q6_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.label_56.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Natureza do Design</span></p></body></html>"))
        self.label_66.setText(_translate("MainWindow", "Fablab"))
        self.Qi4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_59.setText(_translate("MainWindow", "-"))
        self.label_80.setText(_translate("MainWindow", "-"))
        self.T4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_45.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Instrumentação</span></p><p align=\"center\"><span style=\" font-weight:600;\">e Medição</span></p></body></html>"))
        self.label_41.setText(_translate("MainWindow", "Sala 401"))
        self.Q7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_64.setText(_translate("MainWindow", "-"))
        self.label_65.setText(_translate("MainWindow", "-"))
        self.Sx4_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_77.setText(_translate("MainWindow", "-"))
        self.label_78.setText(_translate("MainWindow", "-"))
        self.Sx3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.label_79.setText(_translate("MainWindow", "-"))
        self.label_85.setText(_translate("MainWindow", "-"))
        self.Qi6_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_68.setText(_translate("MainWindow", "-"))
        self.label_67.setText(_translate("MainWindow", "-"))
        self.D4_Tipo.setTitle(_translate("MainWindow", "Horário 4"))
        self.label_98.setText(_translate("MainWindow", "-"))
        self.Sx7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_75.setText(_translate("MainWindow", "-"))
        self.label_76.setText(_translate("MainWindow", "-"))
        self.Sx6_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_73.setText(_translate("MainWindow", "-"))
        self.label_74.setText(_translate("MainWindow", "-"))
        self.Qi7_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_69.setText(_translate("MainWindow", "-"))
        self.label_70.setText(_translate("MainWindow", "-"))
        self.Sx5_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_72.setText(_translate("MainWindow", "-"))
        self.label_71.setText(_translate("MainWindow", "-"))
        self.D6_Tipo.setTitle(_translate("MainWindow", "Horário 6"))
        self.label_96.setText(_translate("MainWindow", "-"))
        self.D5_Tipo.setTitle(_translate("MainWindow", "Horário 5"))
        self.label_97.setText(_translate("MainWindow", "-"))
        self.Sa4_Tipo.setTitle(_translate("MainWindow", "Horário 4"))
        self.label_86.setText(_translate("MainWindow", "-"))
        self.Sa5_Tipo.setTitle(_translate("MainWindow", "Horário 5"))
        self.label_92.setText(_translate("MainWindow", "-"))
        self.Sa7_Tipo.setTitle(_translate("MainWindow", "Horário 7"))
        self.label_94.setText(_translate("MainWindow", "-"))
        self.D7_Tipo.setTitle(_translate("MainWindow", "Horário 7"))
        self.label_95.setText(_translate("MainWindow", "-"))
        self.Sa6_Tipo.setTitle(_translate("MainWindow", "Horário 6"))
        self.label_93.setText(_translate("MainWindow", "-"))
        self.Sx2_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_83.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação</span></p><p align=\"center\"><span style=\" font-weight:600;\"> do Mundo Físico</span></p></body></html>"))
        self.label_84.setText(_translate("MainWindow", "Sala 403"))
        self.Sx1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_81.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Design de Software</span></p></body></html>"))
        self.label_82.setText(_translate("MainWindow", "Sala 403"))
        self.Qi1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_60.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios </span></p><p align=\"center\"><span style=\" font-weight:600;\">da Engenharia</span></p></body></html>"))
        self.label_63.setText(_translate("MainWindow", "Sala 307"))
        self.T1_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.T1_Aula.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Instrumentação </span></p><p align=\"center\"><span style=\" font-weight:600;\">e Medição</span></p></body></html>"))
        self.T1_Sala.setText(_translate("MainWindow", "Sala 401"))
        self.Q1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Design de Software</span></p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "Sala 403"))
        self.S2_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.S2_Aula.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Modelagem e Simulação</span></p><p align=\"center\"><span style=\" font-weight:600;\">do Mundo Físico</span></p></body></html>"))
        self.S2_Sala.setText(_translate("MainWindow", "Sala 403"))
        self.S1_Tipo.setTitle(_translate("MainWindow", "Aula"))
        self.S1_Aula.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios </span></p><p align=\"center\"><span style=\" font-weight:600;\">da Engenharia</span></p></body></html>"))
        self.S1_Sala.setText(_translate("MainWindow", "Sala Marcos Lopes (2)"))
        self.S3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.S3_Aula.setText(_translate("MainWindow", "-"))
        self.S3_Sala.setText(_translate("MainWindow", "-"))
        self.Qi2_Tipo.setTitle(_translate("MainWindow", "Tutoria"))
        self.label_61.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios</span></p><p align=\"center\"><span style=\" font-weight:600;\"> da Engenharia</span></p></body></html>"))
        self.label_62.setText(_translate("MainWindow", "Sala 408"))
        self.Q2_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.label_48.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Grandes Desafios </span></p><p align=\"center\"><span style=\" font-weight:600;\">da Engenharia</span></p></body></html>"))
        self.label_49.setText(_translate("MainWindow", "Sala 403"))
        self.T2_Tipo.setTitle(_translate("MainWindow", "Atendimento"))
        self.T2_Aula.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Design de Software</span></p></body></html>"))
        self.T2_Sala.setText(_translate("MainWindow", "<html><head/><body><p>Sala Alberto Bandeira</p><p>Queiroz (2)</p></body></html>"))
        self.T3_Tipo.setTitle(_translate("MainWindow", "Almoço"))
        self.T3_Aula.setText(_translate("MainWindow", "-"))
        self.T3_Sala.setText(_translate("MainWindow", "-"))
        self.Label_Horarios.setText(_translate("MainWindow", "Horários"))

if __name__ == "__main__":
    app = QtGui.QApplication(sys.argv)
    mainwindow = Ui_MainWindow()
    mainwindow.show()
    sys.exit(app.exec_())