# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Widget_Cadastro(object):
    def setupUi(self):
        self.setObjectName("Widget_Cadastro")
        self.resize(635, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagens/img_icones/system_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setAutoFillBackground(True)
        self.bg_cadastro = QtGui.QLabel(self)
        self.bg_cadastro.setEnabled(True)
        self.bg_cadastro.setGeometry(QtCore.QRect(0, -2, 640, 486))
        self.bg_cadastro.setStyleSheet("background-image: url(:/bg/Imagens/img_bg/tela_cadastro.png);")
        self.bg_cadastro.setText("")
        self.bg_cadastro.setObjectName("bg_cadastro")
        self.input_snapchat = QtGui.QLineEdit(self)
        self.input_snapchat.setGeometry(QtCore.QRect(504, 387, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_snapchat.setFont(font)
        self.input_snapchat.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_snapchat.setFrame(False)
        self.input_snapchat.setObjectName("input_snapchat")
        self.input_instagram = QtGui.QLineEdit(self)
        self.input_instagram.setGeometry(QtCore.QRect(324, 388, 124, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_instagram.setFont(font)
        self.input_instagram.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_instagram.setFrame(False)
        self.input_instagram.setObjectName("input_instagram")
        self.input_fb = QtGui.QLineEdit(self)
        self.input_fb.setGeometry(QtCore.QRect(50, 389, 216, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_fb.setFont(font)
        self.input_fb.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_fb.setFrame(False)
        self.input_fb.setObjectName("input_fb")
        self.combo_curso = QtGui.QComboBox(self)
        self.combo_curso.setGeometry(QtCore.QRect(68, 180, 352, 22))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.combo_curso.setFont(font)
        self.combo_curso.setObjectName("combo_curso")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Imagens/img_icones/adm.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_curso.addItem(icon1, "")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Imagens/img_icones/eco.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_curso.addItem(icon2, "")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Imagens/img_icones/comp.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_curso.addItem(icon3, "")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Imagens/img_icones/mec.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_curso.addItem(icon4, "")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Imagens/img_icones/meca.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.combo_curso.addItem(icon5, "")
        self.combo_semestre = QtGui.QComboBox(self)
        self.combo_semestre.setGeometry(QtCore.QRect(521, 180, 104, 22))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.combo_semestre.setFont(font)
        self.combo_semestre.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.combo_semestre.setFrame(True)
        self.combo_semestre.setObjectName("combo_semestre")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.combo_semestre.addItem("")
        self.input_nome = QtGui.QLineEdit(self)
        self.input_nome.setGeometry(QtCore.QRect(75, 37, 351, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_nome.setFont(font)
        self.input_nome.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_nome.setFrame(False)
        self.input_nome.setEchoMode(QtGui.QLineEdit.Normal)
        self.input_nome.setObjectName("input_nome")
        self.input_nasci = QtGui.QDateEdit(self)
        self.input_nasci.setGeometry(QtCore.QRect(548, 38, 78, 22))
        self.input_nasci.setFrame(False)
        self.input_nasci.setReadOnly(False)
        self.input_nasci.setButtonSymbols(QtGui.QAbstractSpinBox.PlusMinus)
        self.input_nasci.setDate(QtCore.QDate(1997, 1, 1))
        self.input_nasci.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(2020, 12, 31), QtCore.QTime(23, 59, 59)))
        self.input_nasci.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(1900, 9, 14), QtCore.QTime(0, 0, 0)))
        self.input_nasci.setCurrentSection(QtGui.QDateTimeEdit.DaySection)
        self.input_nasci.setCalendarPopup(False)
        self.input_nasci.setObjectName("input_nasci")
        self.input_newuser = QtGui.QLineEdit(self)
        self.input_newuser.setGeometry(QtCore.QRect(82, 85, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_newuser.setFont(font)
        self.input_newuser.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_newuser.setFrame(False)
        self.input_newuser.setObjectName("input_newuser")
        self.input_newpw = QtGui.QLineEdit(self)
        self.input_newpw.setGeometry(QtCore.QRect(270, 86, 103, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_newpw.setFont(font)
        self.input_newpw.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText)
        self.input_newpw.setText("")
        self.input_newpw.setMaxLength(15)
        self.input_newpw.setFrame(False)
        self.input_newpw.setEchoMode(QtGui.QLineEdit.Password)
        self.input_newpw.setObjectName("input_newpw")
        self.input_newpw_conf = QtGui.QLineEdit(self)
        self.input_newpw_conf.setGeometry(QtCore.QRect(521, 85, 103, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_newpw_conf.setFont(font)
        self.input_newpw_conf.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.input_newpw_conf.setText("")
        self.input_newpw_conf.setMaxLength(15)
        self.input_newpw_conf.setFrame(False)
        self.input_newpw_conf.setEchoMode(QtGui.QLineEdit.Password)
        self.input_newpw_conf.setObjectName("input_newpw_conf")
        self.input_email = QtGui.QLineEdit(self)
        self.input_email.setGeometry(QtCore.QRect(63, 351, 314, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_email.setFont(font)
        self.input_email.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_email.setFrame(False)
        self.input_email.setObjectName("input_email")
        self.input_telefone = QtGui.QLineEdit(self)
        self.input_telefone.setGeometry(QtCore.QRect(471, 352, 152, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.input_telefone.setFont(font)
        self.input_telefone.setInputMethodHints(QtCore.Qt.ImhNone)
        self.input_telefone.setFrame(False)
        self.input_telefone.setObjectName("input_telefone")
        self.check_atletica = QtGui.QCheckBox(self)
        self.check_atletica.setGeometry(QtCore.QRect(20, 238, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_atletica.setFont(font)
        self.check_atletica.setObjectName("check_atletica")
        self.check_aisec = QtGui.QCheckBox(self)
        self.check_aisec.setGeometry(QtCore.QRect(20, 258, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_aisec.setFont(font)
        self.check_aisec.setObjectName("check_aisec")
        self.check_bateria = QtGui.QCheckBox(self)
        self.check_bateria.setGeometry(QtCore.QRect(20, 278, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_bateria.setFont(font)
        self.check_bateria.setObjectName("check_bateria")
        self.check_bemgasto = QtGui.QCheckBox(self)
        self.check_bemgasto.setGeometry(QtCore.QRect(20, 298, 150, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_bemgasto.setFont(font)
        self.check_bemgasto.setObjectName("check_bemgasto")
        self.check_designchallenge = QtGui.QCheckBox(self)
        self.check_designchallenge.setGeometry(QtCore.QRect(190, 258, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_designchallenge.setFont(font)
        self.check_designchallenge.setObjectName("check_designchallenge")
        self.check_da = QtGui.QCheckBox(self)
        self.check_da.setGeometry(QtCore.QRect(190, 278, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_da.setFont(font)
        self.check_da.setObjectName("check_da")
        self.check_infinance = QtGui.QCheckBox(self)
        self.check_infinance.setGeometry(QtCore.QRect(390, 238, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_infinance.setFont(font)
        self.check_infinance.setObjectName("check_infinance")
        self.check_junior = QtGui.QCheckBox(self)
        self.check_junior.setGeometry(QtCore.QRect(390, 258, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_junior.setFont(font)
        self.check_junior.setObjectName("check_junior")
        self.check_post = QtGui.QCheckBox(self)
        self.check_post.setGeometry(QtCore.QRect(390, 278, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_post.setFont(font)
        self.check_post.setObjectName("check_post")
        self.check_ligaemp = QtGui.QCheckBox(self)
        self.check_ligaemp.setGeometry(QtCore.QRect(390, 298, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_ligaemp.setFont(font)
        self.check_ligaemp.setObjectName("check_ligaemp")
        self.check_consilium = QtGui.QCheckBox(self)
        self.check_consilium.setGeometry(QtCore.QRect(190, 238, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_consilium.setFont(font)
        self.check_consilium.setObjectName("check_consilium")
        self.check_enactus = QtGui.QCheckBox(self)
        self.check_enactus.setGeometry(QtCore.QRect(190, 298, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_enactus.setFont(font)
        self.check_enactus.setObjectName("check_enactus")
        self.check_gas = QtGui.QCheckBox(self)
        self.check_gas.setGeometry(QtCore.QRect(190, 318, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_gas.setFont(font)
        self.check_gas.setObjectName("check_gas")
        self.check_sementes = QtGui.QCheckBox(self)
        self.check_sementes.setGeometry(QtCore.QRect(390, 318, 200, 20))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.check_sementes.setFont(font)
        self.check_sementes.setObjectName("check_sementes")
        self.botao_fb = QtGui.QCommandLinkButton(self)
        self.botao_fb.setGeometry(QtCore.QRect(11, 384, 27, 27))
        self.botao_fb.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Resources/botaoenviar - 42x42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_fb.setIcon(icon6)
        self.botao_fb.setIconSize(QtCore.QSize(27, 27))
        self.botao_fb.setObjectName("botao_fb")
        self.botao_cadastrar = QtGui.QCommandLinkButton(self)
        self.botao_cadastrar.setEnabled(False)
        self.botao_cadastrar.setGeometry(QtCore.QRect(564, 412, 66, 65))
        self.botao_cadastrar.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Resources/botao_cadastrar_inac.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap("../Resources/botao_cadastrar_act.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_cadastrar.setIcon(icon7)
        self.botao_cadastrar.setIconSize(QtCore.QSize(50, 50))
        self.botao_cadastrar.setDescription("")
        self.botao_cadastrar.setObjectName("botao_cadastrar")
        self.botao_voltar = QtGui.QCommandLinkButton(self)
        self.botao_voltar.setGeometry(QtCore.QRect(7, 437, 91, 36))
        self.botao_voltar.setText("")
        self.botao_voltar.setIcon(icon6)
        self.botao_voltar.setIconSize(QtCore.QSize(27, 27))
        self.botao_voltar.setObjectName("botao_voltar")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.setTabOrder(self.input_nome, self.input_nasci)
        self.setTabOrder(self.input_nasci, self.input_newuser)
        self.setTabOrder(self.input_newuser, self.input_newpw)
        self.setTabOrder(self.input_newpw, self.input_newpw_conf)
        self.setTabOrder(self.input_newpw_conf, self.combo_curso)
        self.setTabOrder(self.combo_curso, self.combo_semestre)
        self.setTabOrder(self.combo_semestre, self.check_atletica)
        self.setTabOrder(self.check_atletica, self.check_aisec)
        self.setTabOrder(self.check_aisec, self.check_bateria)
        self.setTabOrder(self.check_bateria, self.check_bemgasto)
        self.setTabOrder(self.check_bemgasto, self.check_consilium)
        self.setTabOrder(self.check_consilium, self.check_designchallenge)
        self.setTabOrder(self.check_designchallenge, self.check_da)
        self.setTabOrder(self.check_da, self.check_enactus)
        self.setTabOrder(self.check_enactus, self.check_gas)
        self.setTabOrder(self.check_gas, self.check_infinance)
        self.setTabOrder(self.check_infinance, self.check_junior)
        self.setTabOrder(self.check_junior, self.botao_fb)
        self.setTabOrder(self.botao_fb, self.check_post)
        self.setTabOrder(self.check_post, self.check_ligaemp)
        self.setTabOrder(self.check_ligaemp, self.check_sementes)
        self.setTabOrder(self.check_sementes, self.input_email)
        self.setTabOrder(self.input_email, self.input_telefone)
        self.setTabOrder(self.input_telefone, self.input_fb)
        self.setTabOrder(self.input_fb, self.input_instagram)
        self.setTabOrder(self.input_instagram, self.input_snapchat)
        self.setTabOrder(self.input_snapchat, self.botao_voltar)
        self.setTabOrder(self.botao_voltar, self.botao_cadastrar)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Widget_Cadastro", "Cadastro"))
        self.combo_curso.setItemText(0, _translate("Widget_Cadastro", "Administração"))
        self.combo_curso.setItemText(1, _translate("Widget_Cadastro", "Economia"))
        self.combo_curso.setItemText(2, _translate("Widget_Cadastro", "Engenharia da Computação"))
        self.combo_curso.setItemText(3, _translate("Widget_Cadastro", "Engenharia Mecânica"))
        self.combo_curso.setItemText(4, _translate("Widget_Cadastro", "Engenharia Mecatrônica"))
        self.combo_semestre.setItemText(0, _translate("Widget_Cadastro", "1"))
        self.combo_semestre.setItemText(1, _translate("Widget_Cadastro", "2"))
        self.combo_semestre.setItemText(2, _translate("Widget_Cadastro", "3"))
        self.combo_semestre.setItemText(3, _translate("Widget_Cadastro", "4"))
        self.combo_semestre.setItemText(4, _translate("Widget_Cadastro", "5"))
        self.combo_semestre.setItemText(5, _translate("Widget_Cadastro", "6"))
        self.combo_semestre.setItemText(6, _translate("Widget_Cadastro", "7"))
        self.combo_semestre.setItemText(7, _translate("Widget_Cadastro", "8"))
        self.combo_semestre.setItemText(8, _translate("Widget_Cadastro", "9"))
        self.combo_semestre.setItemText(9, _translate("Widget_Cadastro", "10"))
        self.check_atletica.setText(_translate("Widget_Cadastro", "Atlética Insper"))
        self.check_aisec.setText(_translate("Widget_Cadastro", "AISEC"))
        self.check_bateria.setText(_translate("Widget_Cadastro", "Bateria Imperial"))
        self.check_bemgasto.setText(_translate("Widget_Cadastro", "Bem gasto"))
        self.check_designchallenge.setText(_translate("Widget_Cadastro", "Design Challenge"))
        self.check_da.setText(_translate("Widget_Cadastro", "Diretório Acadêmico"))
        self.check_infinance.setText(_translate("Widget_Cadastro", "Infinance"))
        self.check_junior.setText(_translate("Widget_Cadastro", "Insper Junior"))
        self.check_post.setText(_translate("Widget_Cadastro", "Insper Post"))
        self.check_ligaemp.setText(_translate("Widget_Cadastro", "Liga de Empreendedores"))
        self.check_consilium.setText(_translate("Widget_Cadastro", "Consilium Insper"))
        self.check_enactus.setText(_translate("Widget_Cadastro", "Enactus"))
        self.check_gas.setText(_translate("Widget_Cadastro", "Grupo de Ação Social"))
        self.check_sementes.setText(_translate("Widget_Cadastro", "Sementes Culturais"))

import tela_cadastro_rc
