from PyQt4 import QtCore, QtGui

class Widget_calendario(QtGui.QWidget):
    def __init__(self, parent):
        super(Widget_calendario, self).__init__(parent)
        self.setupUi()

    def setupUi(self):        
        self.setObjectName("Widget_calendario")
        self.resize(640, 480)
        self.setMinimumSize(QtCore.QSize(640, 480))
        self.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagens/img_icones/system_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.bg_calendario = QtGui.QLabel(self)
        self.bg_calendario.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.bg_calendario.setStyleSheet("background-image: url(:/tela_calendario/Imagens/img_bg/tela_calendario.png);")
        self.bg_calendario.setText("")
        self.bg_calendario.setObjectName("bg_calendario")
        self.but_Seg = QtGui.QCommandLinkButton(self)
        self.but_Seg.setGeometry(QtCore.QRect(53, 24, 86, 54))
        self.but_Seg.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Imagens/img_botoes/botaoenviar - 42x42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.but_Seg.setIcon(icon1)
        self.but_Seg.setObjectName("but_Seg")
        self.but_Seg_2 = QtGui.QCommandLinkButton(self)
        self.but_Seg_2.setGeometry(QtCore.QRect(51, 84, 88, 51))
        self.but_Seg_2.setText("")
        self.but_Seg_2.setIcon(icon1)
        self.but_Seg_2.setObjectName("but_Seg_2")
        self.but_Seg_4 = QtGui.QCommandLinkButton(self)
        self.but_Seg_4.setGeometry(QtCore.QRect(52, 201, 86, 51))
        self.but_Seg_4.setText("")
        self.but_Seg_4.setIcon(icon1)
        self.but_Seg_4.setObjectName("but_Seg_4")
        self.but_ter_4 = QtGui.QCommandLinkButton(self)
        self.but_ter_4.setGeometry(QtCore.QRect(142, 200, 87, 112))
        self.but_ter_4.setText("")
        self.but_ter_4.setIcon(icon1)
        self.but_ter_4.setObjectName("but_ter_4")
        self.but_ter = QtGui.QCommandLinkButton(self)
        self.but_ter.setGeometry(QtCore.QRect(142, 23, 87, 54))
        self.but_ter.setText("")
        self.but_ter.setIcon(icon1)
        self.but_ter.setObjectName("but_ter")
        self.but_ter_2 = QtGui.QCommandLinkButton(self)
        self.but_ter_2.setGeometry(QtCore.QRect(142, 82, 87, 52))
        self.but_ter_2.setText("")
        self.but_ter_2.setIcon(icon1)
        self.but_ter_2.setObjectName("but_ter_2")
        self.but_Qua = QtGui.QCommandLinkButton(self)
        self.but_Qua.setGeometry(QtCore.QRect(232, 23, 87, 54))
        self.but_Qua.setText("")
        self.but_Qua.setIcon(icon1)
        self.but_Qua.setObjectName("but_Qua")
        self.but_Qua_2 = QtGui.QCommandLinkButton(self)
        self.but_Qua_2.setGeometry(QtCore.QRect(232, 82, 87, 54))
        self.but_Qua_2.setText("")
        self.but_Qua_2.setIcon(icon1)
        self.but_Qua_2.setObjectName("but_Qua_2")
        self.but_Qua_4 = QtGui.QCommandLinkButton(self)
        self.but_Qua_4.setGeometry(QtCore.QRect(232, 201, 86, 110))
        self.but_Qua_4.setText("")
        self.but_Qua_4.setIcon(icon1)
        self.but_Qua_4.setObjectName("but_Qua_4")
        self.but_Qui = QtGui.QCommandLinkButton(self)
        self.but_Qui.setGeometry(QtCore.QRect(321, 24, 84, 52))
        self.but_Qui.setText("")
        self.but_Qui.setIcon(icon1)
        self.but_Qui.setObjectName("but_Qui")
        self.but_Qui_2 = QtGui.QCommandLinkButton(self)
        self.but_Qui_2.setGeometry(QtCore.QRect(321, 82, 84, 52))
        self.but_Qui_2.setText("")
        self.but_Qui_2.setIcon(icon1)
        self.but_Qui_2.setObjectName("but_Qui_2")
        self.but_Qui_5 = QtGui.QCommandLinkButton(self)
        self.but_Qui_5.setGeometry(QtCore.QRect(322, 259, 84, 52))
        self.but_Qui_5.setText("")
        self.but_Qui_5.setIcon(icon1)
        self.but_Qui_5.setObjectName("but_Qui_5")
        self.but_sex = QtGui.QCommandLinkButton(self)
        self.but_sex.setGeometry(QtCore.QRect(412, 24, 84, 55))
        self.but_sex.setText("")
        self.but_sex.setIcon(icon1)
        self.but_sex.setObjectName("but_sex")
        self.but_sex_2 = QtGui.QCommandLinkButton(self)
        self.but_sex_2.setGeometry(QtCore.QRect(409, 82, 87, 53))
        self.but_sex_2.setText("")
        self.but_sex_2.setIcon(icon1)
        self.but_sex_2.setObjectName("but_sex_2")
        self.seg_3 = QtGui.QLabel(self)
        self.seg_3.setGeometry(QtCore.QRect(51, 143, 88, 50))
        self.seg_3.setAlignment(QtCore.Qt.AlignCenter)
        self.seg_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.seg_3.setObjectName("seg_3")
        self.seg_5 = QtGui.QLabel(self)
        self.seg_5.setGeometry(QtCore.QRect(51, 259, 86, 51))
        self.seg_5.setAlignment(QtCore.Qt.AlignCenter)
        self.seg_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.seg_5.setObjectName("seg_5")
        self.seg_6 = QtGui.QLabel(self)
        self.seg_6.setGeometry(QtCore.QRect(52, 319, 86, 51))
        self.seg_6.setAlignment(QtCore.Qt.AlignCenter)
        self.seg_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.seg_6.setObjectName("seg_6")
        self.seg_7 = QtGui.QLabel(self)
        self.seg_7.setGeometry(QtCore.QRect(52, 377, 86, 51))
        self.seg_7.setAlignment(QtCore.Qt.AlignCenter)
        self.seg_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.seg_7.setObjectName("seg_7")
        self.ter_3 = QtGui.QLabel(self)
        self.ter_3.setGeometry(QtCore.QRect(142, 142, 88, 50))
        self.ter_3.setAlignment(QtCore.Qt.AlignCenter)
        self.ter_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ter_3.setObjectName("ter_3")
        self.ter_6 = QtGui.QLabel(self)
        self.ter_6.setGeometry(QtCore.QRect(143, 318, 86, 51))
        self.ter_6.setAlignment(QtCore.Qt.AlignCenter)
        self.ter_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ter_6.setObjectName("ter_6")
        self.ter_7 = QtGui.QLabel(self)
        self.ter_7.setGeometry(QtCore.QRect(143, 376, 86, 51))
        self.ter_7.setAlignment(QtCore.Qt.AlignCenter)
        self.ter_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.ter_7.setObjectName("ter_7")
        self.Qua_3 = QtGui.QLabel(self)
        self.Qua_3.setGeometry(QtCore.QRect(233, 144, 84, 50))
        self.Qua_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Qua_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Qua_3.setObjectName("Qua_3")
        self.Qua_7 = QtGui.QLabel(self)
        self.Qua_7.setGeometry(QtCore.QRect(234, 378, 84, 51))
        self.Qua_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Qua_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Qua_7.setObjectName("Qua_7")
        self.Qua_6 = QtGui.QLabel(self)
        self.Qua_6.setGeometry(QtCore.QRect(234, 320, 84, 51))
        self.Qua_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Qua_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Qua_6.setObjectName("Qua_6")
        self.Qui_3 = QtGui.QLabel(self)
        self.Qui_3.setGeometry(QtCore.QRect(322, 143, 84, 50))
        self.Qui_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Qui_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Qui_3.setObjectName("Qui_3")
        self.Qui_6 = QtGui.QLabel(self)
        self.Qui_6.setGeometry(QtCore.QRect(323, 319, 84, 51))
        self.Qui_6.setAlignment(QtCore.Qt.AlignCenter)
        self.Qui_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Qui_6.setObjectName("Qui_6")
        self.Qui_7 = QtGui.QLabel(self)
        self.Qui_7.setGeometry(QtCore.QRect(323, 377, 84, 51))
        self.Qui_7.setAlignment(QtCore.Qt.AlignCenter)
        self.Qui_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Qui_7.setObjectName("Qui_7")
        self.Qui_4 = QtGui.QLabel(self)
        self.Qui_4.setGeometry(QtCore.QRect(322, 201, 84, 51))
        self.Qui_4.setAlignment(QtCore.Qt.AlignCenter)
        self.Qui_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.Qui_4.setObjectName("Qui_4")
        self.sex_6 = QtGui.QLabel(self)
        self.sex_6.setGeometry(QtCore.QRect(412, 320, 84, 51))
        self.sex_6.setAlignment(QtCore.Qt.AlignCenter)
        self.sex_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sex_6.setObjectName("sex_6")
        self.sex_3 = QtGui.QLabel(self)
        self.sex_3.setGeometry(QtCore.QRect(411, 144, 84, 50))
        self.sex_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sex_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sex_3.setObjectName("sex_3")
        self.sex_4 = QtGui.QLabel(self)
        self.sex_4.setGeometry(QtCore.QRect(411, 202, 84, 51))
        self.sex_4.setAlignment(QtCore.Qt.AlignCenter)
        self.sex_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sex_4.setObjectName("sex_4")
        self.sab_1 = QtGui.QLabel(self)
        self.sab_1.setGeometry(QtCore.QRect(502, 26, 62, 51))
        self.sab_1.setAlignment(QtCore.Qt.AlignCenter)
        self.sab_1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sab_1.setObjectName("sab_1")
        self.sex_5 = QtGui.QLabel(self)
        self.sex_5.setGeometry(QtCore.QRect(411, 258, 84, 51))
        self.sex_5.setAlignment(QtCore.Qt.AlignCenter)
        self.sex_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sex_5.setObjectName("sex_5")
        self.botao_salvar_calendario = QtGui.QCommandLinkButton(self)
        self.botao_salvar_calendario.setGeometry(QtCore.QRect(524, 437, 106, 37))
        self.botao_salvar_calendario.setText("")
        self.botao_salvar_calendario.setIcon(icon1)
        self.botao_salvar_calendario.setObjectName("botao_salvar_calendario")
        self.botao_voltar_calendario = QtGui.QCommandLinkButton(self)
        self.botao_voltar_calendario.setGeometry(QtCore.QRect(6, 436, 92, 39))
        self.botao_voltar_calendario.setText("")
        self.botao_voltar_calendario.setIcon(icon1)
        self.botao_voltar_calendario.setObjectName("botao_voltar_calendario")
        self.sab_2 = QtGui.QLabel(self)
        self.sab_2.setGeometry(QtCore.QRect(501, 81, 62, 51))
        self.sab_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sab_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sab_2.setObjectName("sab_2")
        self.sab_3 = QtGui.QLabel(self)
        self.sab_3.setGeometry(QtCore.QRect(501, 142, 62, 51))
        self.sab_3.setAlignment(QtCore.Qt.AlignCenter)
        self.sab_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sab_3.setObjectName("sab_3")
        self.sab_4 = QtGui.QLabel(self)
        self.sab_4.setGeometry(QtCore.QRect(501, 201, 62, 51))
        self.sab_4.setAlignment(QtCore.Qt.AlignCenter)
        self.sab_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sab_4.setObjectName("sab_4")
        self.sab_5 = QtGui.QLabel(self)
        self.sab_5.setGeometry(QtCore.QRect(501, 259, 62, 51))
        self.sab_5.setAlignment(QtCore.Qt.AlignCenter)
        self.sab_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sab_5.setObjectName("sab_5")
        self.sab_6 = QtGui.QLabel(self)
        self.sab_6.setGeometry(QtCore.QRect(501, 319, 62, 51))
        self.sab_6.setAlignment(QtCore.Qt.AlignCenter)
        self.sab_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sab_6.setObjectName("sab_6")
        self.sab_7 = QtGui.QLabel(self)
        self.sab_7.setGeometry(QtCore.QRect(502, 378, 62, 51))
        self.sab_7.setAlignment(QtCore.Qt.AlignCenter)
        self.sab_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sab_7.setObjectName("sab_7")
        self.dom_1 = QtGui.QLabel(self)
        self.dom_1.setGeometry(QtCore.QRect(569, 25, 62, 51))
        self.dom_1.setAlignment(QtCore.Qt.AlignCenter)
        self.dom_1.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dom_1.setObjectName("dom_1")
        self.dom_2 = QtGui.QLabel(self)
        self.dom_2.setGeometry(QtCore.QRect(570, 83, 62, 51))
        self.dom_2.setAlignment(QtCore.Qt.AlignCenter)
        self.dom_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dom_2.setObjectName("dom_2")
        self.dom_3 = QtGui.QLabel(self)
        self.dom_3.setGeometry(QtCore.QRect(568, 142, 62, 51))
        self.dom_3.setAlignment(QtCore.Qt.AlignCenter)
        self.dom_3.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dom_3.setObjectName("dom_3")
        self.dom_4 = QtGui.QLabel(self)
        self.dom_4.setGeometry(QtCore.QRect(569, 201, 62, 51))
        self.dom_4.setAlignment(QtCore.Qt.AlignCenter)
        self.dom_4.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dom_4.setObjectName("dom_4")
        self.dom_5 = QtGui.QLabel(self)
        self.dom_5.setGeometry(QtCore.QRect(569, 262, 62, 51))
        self.dom_5.setAlignment(QtCore.Qt.AlignCenter)
        self.dom_5.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dom_5.setObjectName("dom_5")
        self.dom_6 = QtGui.QLabel(self)
        self.dom_6.setGeometry(QtCore.QRect(569, 317, 62, 51))
        self.dom_6.setAlignment(QtCore.Qt.AlignCenter)
        self.dom_6.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dom_6.setObjectName("dom_6")
        self.dom_7 = QtGui.QLabel(self)
        self.dom_7.setGeometry(QtCore.QRect(570, 378, 62, 51))
        self.dom_7.setAlignment(QtCore.Qt.AlignCenter)
        self.dom_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.dom_7.setObjectName("dom_7")
        self.sex_7 = QtGui.QLabel(self)
        self.sex_7.setGeometry(QtCore.QRect(411, 380, 84, 51))
        self.sex_7.setAlignment(QtCore.Qt.AlignCenter)
        self.sex_7.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextEditable|QtCore.Qt.TextEditorInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.sex_7.setObjectName("sex_7")
        self.bg_calendario.raise_()
        self.but_Seg.raise_()
        self.but_Seg_2.raise_()
        self.but_Seg_4.raise_()
        self.but_ter_4.raise_()
        self.but_ter.raise_()
        self.but_ter_2.raise_()
        self.but_Qua.raise_()
        self.but_Qua_2.raise_()
        self.but_Qua_4.raise_()
        self.but_Qui.raise_()
        self.but_Qui_2.raise_()
        self.but_Qui_5.raise_()
        self.but_sex.raise_()
        self.but_sex_2.raise_()
        self.seg_3.raise_()
        self.seg_6.raise_()
        self.seg_7.raise_()
        self.seg_5.raise_()
        self.ter_3.raise_()
        self.ter_6.raise_()
        self.ter_7.raise_()
        self.Qua_3.raise_()
        self.Qua_7.raise_()
        self.Qua_6.raise_()
        self.Qui_3.raise_()
        self.Qui_6.raise_()
        self.Qui_7.raise_()
        self.Qui_4.raise_()
        self.sex_6.raise_()
        self.sex_3.raise_()
        self.sex_4.raise_()
        self.sab_1.raise_()
        self.sex_5.raise_()
        self.botao_salvar_calendario.raise_()
        self.botao_voltar_calendario.raise_()
        self.sab_2.raise_()
        self.sab_3.raise_()
        self.sab_4.raise_()
        self.sab_5.raise_()
        self.sab_6.raise_()
        self.sab_7.raise_()
        self.dom_1.raise_()
        self.dom_2.raise_()
        self.dom_3.raise_()
        self.dom_4.raise_()
        self.dom_5.raise_()
        self.dom_6.raise_()
        self.dom_7.raise_()
        self.sex_7.raise_()

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName()

    def retranslateUi(self, Widget_calendario):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Widget_calendario", "Integrator"))
        self.seg_3.setText(_translate("Widget_calendario", "-"))
        self.seg_5.setText(_translate("Widget_calendario", "-"))
        self.seg_6.setText(_translate("Widget_calendario", "-"))
        self.seg_7.setText(_translate("Widget_calendario", "-"))
        self.ter_3.setText(_translate("Widget_calendario", "-"))
        self.ter_6.setText(_translate("Widget_calendario", "-"))
        self.ter_7.setText(_translate("Widget_calendario", "-"))
        self.Qua_3.setText(_translate("Widget_calendario", "-"))
        self.Qua_7.setText(_translate("Widget_calendario", "-"))
        self.Qua_6.setText(_translate("Widget_calendario", "-"))
        self.Qui_3.setText(_translate("Widget_calendario", "-"))
        self.Qui_6.setText(_translate("Widget_calendario", "-"))
        self.Qui_7.setText(_translate("Widget_calendario", "-"))
        self.Qui_4.setText(_translate("Widget_calendario", "-"))
        self.sex_6.setText(_translate("Widget_calendario", "-"))
        self.sex_3.setText(_translate("Widget_calendario", "-"))
        self.sex_4.setText(_translate("Widget_calendario", "-"))
        self.sab_1.setText(_translate("Widget_calendario", "-"))
        self.sex_5.setText(_translate("Widget_calendario", "-"))
        self.sab_2.setText(_translate("Widget_calendario", "-"))
        self.sab_3.setText(_translate("Widget_calendario", "-"))
        self.sab_4.setText(_translate("Widget_calendario", "-"))
        self.sab_5.setText(_translate("Widget_calendario", "-"))
        self.sab_6.setText(_translate("Widget_calendario", "-"))
        self.sab_7.setText(_translate("Widget_calendario", "-"))
        self.dom_1.setText(_translate("Widget_calendario", "-"))
        self.dom_2.setText(_translate("Widget_calendario", "-"))
        self.dom_3.setText(_translate("Widget_calendario", "-"))
        self.dom_4.setText(_translate("Widget_calendario", "-"))
        self.dom_5.setText(_translate("Widget_calendario", "-"))
        self.dom_6.setText(_translate("Widget_calendario", "-"))
        self.dom_7.setText(_translate("Widget_calendario", "-"))
        self.sex_7.setText(_translate("Widget_calendario", "-"))

import tela_calendario_rc
