# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_editarperfil.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_tela_editar_perfil(object):
    def setupUi(self):
        self.setObjectName("tela_editar_perfil")
        self.resize(640, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sizePolicy().hasHeightForWidth())
        self.setSizePolicy(sizePolicy)
        self.setMinimumSize(QtCore.QSize(640, 480))
        self.setMaximumSize(QtCore.QSize(640, 480))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Imagens/img_icones/system_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.bg_perfil = QtGui.QLabel(self)
        self.bg_perfil.setGeometry(QtCore.QRect(0, 0, 640, 480))
        self.bg_perfil.setStyleSheet("background-image: url(:/tela_editarperfil/Imagens/img_bg/tela_editarperfil.png);")
        self.bg_perfil.setText("")
        self.bg_perfil.setObjectName("bg_perfil")
        self.output_nome = QtGui.QLineEdit(self)
        self.output_nome.setGeometry(QtCore.QRect(73, 102, 353, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_nome.setFont(font)
        self.output_nome.setFrame(False)
        self.output_nome.setReadOnly(False)
        self.output_nome.setObjectName("output_nome")
        self.output_email = QtGui.QLineEdit(self)
        self.output_email.setGeometry(QtCore.QRect(271, 63, 353, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_email.setFont(font)
        self.output_email.setFrame(False)
        self.output_email.setReadOnly(False)
        self.output_email.setObjectName("output_email")
        self.output_curso = QtGui.QLineEdit(self)
        self.output_curso.setGeometry(QtCore.QRect(65, 155, 353, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_curso.setFont(font)
        self.output_curso.setFrame(False)
        self.output_curso.setReadOnly(False)
        self.output_curso.setObjectName("output_curso")
        self.output_entidades = QtGui.QLineEdit(self)
        self.output_entidades.setGeometry(QtCore.QRect(195, 365, 427, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_entidades.setFont(font)
        self.output_entidades.setFrame(False)
        self.output_entidades.setReadOnly(True)
        self.output_entidades.setObjectName("output_entidades")
        self.output_colegio = QtGui.QLineEdit(self)
        self.output_colegio.setGeometry(QtCore.QRect(324, 194, 298, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_colegio.setFont(font)
        self.output_colegio.setFrame(False)
        self.output_colegio.setReadOnly(False)
        self.output_colegio.setObjectName("output_colegio")
        self.output_transporte = QtGui.QLineEdit(self)
        self.output_transporte.setGeometry(QtCore.QRect(395, 251, 227, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_transporte.setFont(font)
        self.output_transporte.setFrame(False)
        self.output_transporte.setReadOnly(False)
        self.output_transporte.setObjectName("output_transporte")
        self.output_telefone = QtGui.QLineEdit(self)
        self.output_telefone.setGeometry(QtCore.QRect(82, 192, 151, 22))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_telefone.setFont(font)
        self.output_telefone.setFrame(False)
        self.output_telefone.setReadOnly(False)
        self.output_telefone.setObjectName("output_telefone")
        self.output_bairro = QtGui.QLineEdit(self)
        self.output_bairro.setGeometry(QtCore.QRect(69, 251, 151, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_bairro.setFont(font)
        self.output_bairro.setFrame(False)
        self.output_bairro.setReadOnly(False)
        self.output_bairro.setObjectName("output_bairro")
        self.output_nascimento = QtGui.QLineEdit(self)
        self.output_nascimento.setGeometry(QtCore.QRect(546, 102, 78, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(11)
        self.output_nascimento.setFont(font)
        self.output_nascimento.setFrame(False)
        self.output_nascimento.setReadOnly(False)
        self.output_nascimento.setObjectName("output_nascimento")
        self.output_semestre = QtGui.QLineEdit(self)
        self.output_semestre.setGeometry(QtCore.QRect(516, 155, 104, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_semestre.setFont(font)
        self.output_semestre.setFrame(False)
        self.output_semestre.setReadOnly(False)
        self.output_semestre.setObjectName("output_semestre")
        self.output_snapchat = QtGui.QLineEdit(self)
        self.output_snapchat.setGeometry(QtCore.QRect(503, 307, 118, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_snapchat.setFont(font)
        self.output_snapchat.setFrame(False)
        self.output_snapchat.setReadOnly(False)
        self.output_snapchat.setObjectName("output_snapchat")
        self.output_instagram = QtGui.QLineEdit(self)
        self.output_instagram.setGeometry(QtCore.QRect(323, 310, 123, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_instagram.setFont(font)
        self.output_instagram.setFrame(False)
        self.output_instagram.setReadOnly(False)
        self.output_instagram.setObjectName("output_instagram")
        self.output_facebook = QtGui.QLineEdit(self)
        self.output_facebook.setGeometry(QtCore.QRect(50, 310, 217, 23))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_facebook.setFont(font)
        self.output_facebook.setFrame(False)
        self.output_facebook.setReadOnly(False)
        self.output_facebook.setObjectName("output_facebook")
        self.output_nascimento_2 = QtGui.QLineEdit(self)
        self.output_nascimento_2.setGeometry(QtCore.QRect(78, 64, 116, 21))
        font = QtGui.QFont()
        font.setFamily("Myriad Pro")
        font.setPointSize(12)
        self.output_nascimento_2.setFont(font)
        self.output_nascimento_2.setFrame(False)
        self.output_nascimento_2.setReadOnly(True)
        self.output_nascimento_2.setObjectName("output_nascimento_2")
        self.botao_voltar_editarperfil = QtGui.QCommandLinkButton(self)
        self.botao_voltar_editarperfil.setGeometry(QtCore.QRect(10, 436, 90, 37))
        self.botao_voltar_editarperfil.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Imagens/img_botoes/botaoenviar - 42x42.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.botao_voltar_editarperfil.setIcon(icon1)
        self.botao_voltar_editarperfil.setObjectName("botao_voltar_editarperfil")
        self.botao_enviaredicoes = QtGui.QCommandLinkButton(self)
        self.botao_enviaredicoes.setGeometry(QtCore.QRect(537, 435, 90, 36))
        self.botao_enviaredicoes.setText("")
        self.botao_enviaredicoes.setIcon(icon1)
        self.botao_enviaredicoes.setObjectName("botao_enviaredicoes")

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("tela_editar_perfil", "Integrator"))

import tela_editarperfil_rc
